from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def read_text(relative_path: str) -> str:
    path = ROOT / relative_path

    if not path.exists():
        raise SystemExit(f"File not found: {relative_path}")

    return path.read_text(encoding="utf-8")


def require_contains(relative_path: str, fragments: list[str]) -> None:
    text = read_text(relative_path)
    missing = [fragment for fragment in fragments if fragment not in text]

    if missing:
        print(f"{relative_path} is missing required fragments:")
        for fragment in missing:
            print(f" - {fragment}")
        raise SystemExit(1)


def main() -> None:
    require_contains(
        "frontend/src/hooks/useAdminAuditActions.js",
        [
            'import { formatApiError } from "../utils/apiErrors";',
            'import { getAdminAuditEvents } from "../api/client";',
            "export function useAdminAuditActions({",
            "setAdminData,",
            "setAdminDataLoadedAt,",
            "setAdminLoading,",
            "setError,",
            "clearSelectedAuditEvent,",
            "getNowLabel,",
            "async function handleApplyAuditFilters(filters)",
            "setAdminLoading(true);",
            "setError(\"\");",
            "clearSelectedAuditEvent();",
            "const auditEvents = await getAdminAuditEvents(filters);",
            "setAdminData((current) => ({",
            "auditEvents,",
            "setAdminDataLoadedAt(getNowLabel());",
            "setError(formatApiError(err,",
            "throw err;",
            "setAdminLoading(false);",
            "handleApplyAuditFilters,",
        ],
    )

    require_contains(
        "frontend/src/hooks/useAdminDataLoader.js",
        [
            'import { formatApiError } from "../utils/apiErrors";',
            "getAdminAuditEvents,",
            "getAdminOrganizations,",
            "getAdminPermissions,",
            "getAdminRoles,",
            "getAdminUsers,",
            "getOrgLearningGroups,",
            "EMPTY_ADMIN_DATA,",
            "getNowLabel,",
            "sortGroups,",
            "sortOrganizations,",
            "sortUsers,",
            "export function useAdminDataLoader({",
                        "export const ADMIN_USERS_FAST_PATH_LIMIT = 200;",
            "export function buildAdminUsersFastPathFilters(usersFilters = {}, roles = [])",
            "const { usersFilters = {} } = options || {};",
            "async function loadAdminData(options = {})",
            "async function refreshAdminGroups()",
            "groups: sortGroups(groups),",
            "async function refreshAdminOrganizations()",
            "organizations: sortOrganizations(organizations),",
            "async function refreshAdminUsers(usersFilters = {}, roles = [])",
            "setAdminData((current) => ({",
            "...current,",
            "users: sortUsers(users),",
            "setAdminLoading(true);",
            "setError(\"\");",
            "await Promise.all([",
            "getAdminUsers(buildAdminUsersFastPathFilters(usersFilters, roles));",
            "getAdminOrganizations(),",
            "getOrgLearningGroups(),",
            "getAdminRoles(),",
            "getAdminPermissions(),",
            "getAdminAuditEvents(),",
            "groups: sortGroups(groups),",
            "setAdminDataLoadedAt(getNowLabel());",
            "setError(formatApiError(err,",
            "setAdminData(EMPTY_ADMIN_DATA);",
            "setAdminDataLoadedAt(\"\");",
            "setAdminLoading(false);",
            "loadAdminData,",
            "refreshAdminGroups,",
            "refreshAdminOrganizations,",
            "refreshAdminUsers,",
        ],
    )

    require_contains(
        "frontend/src/hooks/useAdminDetailActions.js",
        [
            "getAdminAuditEventDetail,",
            "getAdminOrganizationDetail,",
            "getAdminPermissionDetail,",
            "getAdminRoleDetail,",
            "getAdminUserDetail,",
            "getOrgLearningGroupDetail,",
            "export function useAdminDetailActions({",
            "openSelection,",
            "async function handleOpenUser(userId)",
            "load: () => getAdminUserDetail(userId),",
            "async function handleOpenOrganization(organizationId)",
            "load: () => getAdminOrganizationDetail(organizationId),",
            "async function handleOpenGroup(groupId)",
            "load: () => getOrgLearningGroupDetail(groupId),",
            "async function handleOpenRole(roleId)",
            "load: () => getAdminRoleDetail(roleId),",
            "async function handleOpenPermission(permissionId)",
            "load: () => getAdminPermissionDetail(permissionId),",
            "async function handleOpenAuditEvent(auditEventId)",
            "load: () => getAdminAuditEventDetail(auditEventId),",
            "handleOpenUser,",
            "handleOpenOrganization,",
            "handleOpenGroup,",
            "handleOpenRole,",
            "handleOpenPermission,",
            "handleOpenAuditEvent,",
        ],
    )

    require_contains(
        "frontend/src/hooks/useAdminEntityActions.js",
        [
            "activateAdminUser,",
            "assignAdminRolePermission,",
            "assignAdminUserRole,",
            "createAdminOrganization,",
            "createAdminRole,",
            "createAdminUser,",
            "createOrgLearningGroup,",
            "deactivateAdminUser,",
            "deleteAdminOrganization,",
            "deleteAdminRole,",
            "deleteOrgLearningGroup,",
            "removeAdminRolePermission,",
            "removeAdminUserRole,",
            "resetAdminUserPassword,",
            "updateAdminOrganization,",
            "updateAdminRole,",
            "updateAdminUser,",
            "updateOrgLearningGroup,",
            "removeAdminCollectionItem,",
            "replaceAdminCollectionItem,",
            "upsertAdminCollectionItem,",
            "sortGroups,",
            "sortOrganizations,",
            "sortRoles,",
            "sortUsers,",
            "export function useAdminEntityActions({",
            "async function handleCreateUser(payload)",
            "upsertAdminCollectionItem(setAdminData, \"users\", created, sortUsers);",
            "async function handleUpdateUser(userId, payload)",
            "replaceAdminCollectionItem(setAdminData, \"users\", updated, sortUsers);",
            "async function handleResetUserPassword(userId, password)",
            "async function handleActivateUser(userId)",
            "async function handleDeactivateUser(userId)",
            "async function handleAssignUserRole(userId, payload)",
            "async function handleRemoveUserRole(userId, userRoleId)",
            "async function handleCreateOrganization(payload)",
            "upsertAdminCollectionItem(setAdminData, \"organizations\", created, sortOrganizations);",
            "async function handleUpdateOrganization(organizationId, payload)",
            "async function handleDeleteOrganization(organizationId)",
            "removeAdminCollectionItem(setAdminData, \"organizations\", organizationId);",
            "clearSelectedOrganization();",
            "async function handleCreateGroup(payload)",
            "upsertAdminCollectionItem(setAdminData, \"groups\", created, sortGroups);",
            "async function handleUpdateGroup(groupId, payload)",
            "async function handleDeleteGroup(groupId)",
            "removeAdminCollectionItem(setAdminData, \"groups\", groupId, sortGroups);",
            "if (selectedGroup?.id === groupId)",
            "clearSelectedGroup();",
            "async function handleCreateRole(payload)",
            "upsertAdminCollectionItem(setAdminData, \"roles\", created, sortRoles);",
            "async function handleUpdateRole(roleId, payload)",
            "async function handleDeleteRole(roleId)",
            "if (selectedRole?.id === roleId)",
            "clearSelectedRole();",
            "async function handleAssignRolePermission(roleId, payload)",
            "async function handleRemoveRolePermission(roleId, rolePermissionId)",
            "handleCreateUser,",
            "handleDeleteGroup,",
            "handleAssignRolePermission,",
            "handleRemoveRolePermission,",
        ],
    )

    require_contains(
        "frontend/src/hooks/useAdminSelections.js",
        [
            'import { formatApiError } from "../utils/apiErrors";',
            'import { useState } from "react";',
            "export function useAdminSelections()",
            "const [selectedUser, setSelectedUser] = useState(null);",
            "const [selectedOrganization, setSelectedOrganization] = useState(null);",
            "const [selectedGroup, setSelectedGroup] = useState(null);",
            "const [selectedRole, setSelectedRole] = useState(null);",
            "const [selectedPermission, setSelectedPermission] = useState(null);",
            "const [selectedAuditEvent, setSelectedAuditEvent] = useState(null);",
            "function clearSelectedUser()",
            "function clearSelectedOrganization()",
            "function clearSelectedGroup()",
            "function clearSelectedRole()",
            "function clearSelectedPermission()",
            "function clearSelectedAuditEvent()",
            "function clearAllSelections()",
            "clearSelectedUser();",
            "clearSelectedOrganization();",
            "clearSelectedGroup();",
            "clearSelectedRole();",
            "clearSelectedPermission();",
            "clearSelectedAuditEvent();",
            "async function openSelection({ setValue, setLoading, setError, load })",
            "setValue(null);",
            "setError(\"\");",
            "setLoading(true);",
            "const detail = await load();",
            "setValue(detail);",
            "return detail;",
            "setError(formatApiError(err,",
            "return null;",
            "setLoading(false);",
            "openSelection,",
            "clearAllSelections,",
            "clearSelectedAuditEvent,",
        ],
    )

    require_contains(
        "frontend/src/hooks/useAppNavigation.js",
        [
            'import { useNavigate } from "react-router-dom";',
            'import { getAdminPathForPage } from "../utils/adminRoutes";',
            'import { PUBLIC_ROUTE_MAP } from "../utils/publicRoutes";',
            "export function useAppNavigation({ setCurrentPage })",
            "const navigate = useNavigate();",
            "function handleNavigatePublicPage(pageKey)",
            "if (pageKey === \"dashboard\" || pageKey === \"admin\")",
            "navigate(\"/admin\");",
            "navigate(PUBLIC_ROUTE_MAP[pageKey] || \"/\");",
            "function handleNavigateAdminPage(pageKey)",
            "const path = getAdminPathForPage(pageKey);",
            "setCurrentPage(pageKey);",
            "navigate(path);",
            "function handleOpenPublicCourse(courseSlug)",
            "navigate(`/courses/${courseSlug}`);",
            "handleNavigatePublicPage,",
            "handleNavigateAdminPage,",
            "handleOpenPublicCourse,",
        ],
    )

    require_contains(
        "frontend/src/hooks/useAppRouteState.js",
        [
            "getAdminPageFromPathname,",
            "isAdminPathname,",
            'import { getPublicPageFromPathname } from "../utils/publicRoutes";',
            'import { userHasRole } from "../utils/adminState";',
            "export function useAppRouteState({",
            "pathname,",
            "currentPage,",
            "user,",
            "initializingAuth,",
            "const isAdminRoute = isAdminPathname(pathname);",
            "const adminRoutePage = getAdminPageFromPathname(pathname);",
            "const isUnknownAdminRoute = isAdminRoute && !adminRoutePage;",
            "const activeAdminPage = adminRoutePage || currentPage;",
            "const currentPublicPage = getPublicPageFromPathname(pathname);",
            "const isAdmin = userHasRole(user, \"admin\");",
            "const authBadgeText = initializingAuth",
            "? \"initializing\"",
            "? \"authenticated\"",
            ": \"guest\";",
            "const authBadgeTone = initializingAuth",
            "? \"amber\"",
            "? \"blue\"",
            ": \"gray\";",
            "isAdminRoute,",
            "adminRoutePage,",
            "isUnknownAdminRoute,",
            "activeAdminPage,",
            "currentPublicPage,",
            "isAdmin,",
            "authBadgeText,",
            "authBadgeTone,",
        ],
    )

    require_contains(
        "frontend/src/hooks/useAuthFlow.js",
        [
            'import { formatApiError } from "../utils/apiErrors";',
            'import { useNavigate } from "react-router-dom";',
            'checkAdminRbac,',
            'clearToken,',
            'getCurrentUser,',
            'getStoredToken,',
            'login,',
            'registerUser,',
            'storeToken,',
            'import { EMPTY_ADMIN_DATA, userHasRole } from "../utils/adminState";',
            'function getPostAuthPublicPage(user)',
            'if (userHasRole(user, "org_rep"))',
            'return "organization";',
            'userHasRole(user, "ministry_admin") ? "ministry" : "account"',
            'function getPostAuthPublicPath(user)',
            'return "/organization";',
            'userHasRole(user, "ministry_admin") ? "/ministry" : "/account"',
            'export function useAuthFlow({',
            'completePendingEnrollmentIfNeeded,',
            'const navigate = useNavigate();',
            'async function bootstrapAuthState()',
            'const token = getStoredToken();',
            'if (!token)',
            'setAdminData(EMPTY_ADMIN_DATA);',
            'const currentUser = await getCurrentUser();',
            'if (userHasRole(currentUser, "admin"))',
            'await loadAdminData();',
            'setCurrentPage(getPostAuthPublicPage(currentUser));',
            'clearToken();',
            'clearAllSelections();',
            'async function handleRegister(payload)',
            'setAuthLoading(true);',
            'setError("");',
            'return await registerUser(payload);',
            'setError(formatApiError(err, "Не удалось отправить заявку на регистрацию."));',
            'throw err;',
            'setAuthLoading(false);',
            'navigate("/admin", { replace: true });',
            'await completePendingEnrollmentIfNeeded();',
            'navigate(getPostAuthPublicPath(currentUser), { replace: true });',
            'async function handleLogin(event)',
            'event.preventDefault();',
            'await login(email, password);',
            'async function handleRbacCheck()',
            'const data = await checkAdminRbac();',
            'function handleLogout()',
            'clearToken();',
            'setAdminLoading(false);',
            'setInitializingAuth(false);',
            'bootstrapAuthState,',
            'handleRegister,',
            'handleLogin,',
            'handleRbacCheck,',
            'handleLogout,',
        ]
    )

    require_contains(
        "frontend/src/hooks/usePageMeta.js",
        [
            'import { useEffect } from "react";',
            'import { useLocation } from "react-router-dom";',
            'import { isAdminPathname } from "../utils/adminRoutes";',
            "buildPublicMeta,",
            "ensureMetaDescriptionTag,",
            "const ADMIN_META = {",
            "title:",
            "description:",
            "export function usePageMeta()",
            "const location = useLocation();",
            "useEffect(() => {",
            "const meta = isAdminPathname(location.pathname)",
            "? ADMIN_META",
            ": buildPublicMeta(location.pathname);",
            "document.title = meta.title;",
            "const metaDescriptionTag = ensureMetaDescriptionTag();",
            "metaDescriptionTag.setAttribute(\"content\", meta.description);",
            "}, [location.pathname]);",
            "return location;",
        ],
    )

    require_contains(
        "frontend/src/hooks/usePendingEnrollment.js",
        [
            'import { formatApiError } from "../utils/apiErrors";',
            "enrollAccountCourse,",
            "getPublicCourseDetail,",
            "export function usePendingEnrollment({ setError })",
            "function getPendingEnrollmentSlug()",
            "localStorage.getItem(\"obrportal_pending_enrollment_slug\")",
            "function clearPendingEnrollmentSlug()",
            "localStorage.removeItem(\"obrportal_pending_enrollment_slug\")",
            "function setAccountEnrollmentNotice(notice)",
            "sessionStorage.setItem(\"obrportal_account_notice\", JSON.stringify(notice));",
            "async function completePendingEnrollmentIfNeeded()",
            "const pendingSlug = getPendingEnrollmentSlug();",
            "if (!pendingSlug)",
            "const course = await getPublicCourseDetail(pendingSlug);",
            "await enrollAccountCourse(course.id);",
            "clearPendingEnrollmentSlug();",
            "setAccountEnrollmentNotice({",
            "status: \"created\"",
            "if (err.status === 409)",
            "status: \"already_enrolled\"",
            "if (err.status === 404)",
            "status: \"not_found\"",
            "setError(formatApiError(err,",
            "status: \"failed\"",
            "completePendingEnrollmentIfNeeded,",
        ],
    )

    require_contains(
        "frontend/src/hooks/useSystemStatus.js",
        [
            'import { useState } from "react";',
            'import { getHealth, getReady } from "../api/client";',
            "export function useSystemStatus()",
            "const [health, setHealth] = useState(null);",
            "const [ready, setReady] = useState(null);",
            "async function loadSystemStatus()",
            "await Promise.all([",
            "getHealth(),",
            "getReady(),",
            "setHealth(healthData);",
            "setReady(readyData);",
            "setHealth({ status: \"error\" });",
            "setReady({ status: \"error\" });",
            "health,",
            "ready,",
            "loadSystemStatus,",
        ],
    )

    require_contains(
        "frontend/src/components/layout/AppShell.jsx",
        [
            'import { Link } from "react-router-dom";',
            'import { StatusBadge } from "../ui/StatusBadge";',
            'import { ADMIN_ROUTE_ITEMS } from "../../utils/adminRoutes";',
            "export function AppShell({",
            "health,",
            "ready,",
            "user,",
            "isAdmin,",
            "authBadgeText,",
            "authBadgeTone,",
            "currentPage,",
            "onPageChange,",
            "counts,",
            "adminLoading,",
            "adminDataLoadedAt,",
            "children,",
            "function getCount(key)",
            "const countMap = {",
            "audit: counts?.auditEvents,",
            "\"audit-events\": counts?.auditEvents,",
            "Object.prototype.hasOwnProperty.call(countMap, key)",
            "function formatCountBadge(value)",
            "if (value > 999)",
            "return \"999+\";",
            "ADMIN_ROUTE_ITEMS.find((item) => item.key === currentPage)?.label",
            "const adminApiStatus = adminLoading",
            "const adminApiTone = adminLoading",
            "health?.status === \"ok\" ? \"green\" : \"red\"",
            "ready?.status === \"ok\" ? \"green\" : \"red\"",
            "{isAdmin && <StatusBadge tone=\"amber\">admin</StatusBadge>}",
            "ADMIN_ROUTE_ITEMS.map((item) => {",
            "const count = getCount(item.key);",
            "const isActive = currentPage === item.key;",
            "<Link",
            "to={item.path}",
            "aria-current={isActive ? \"page\" : undefined}",
            "onClick={() => onPageChange(item.key)}",
            "formatCountBadge(count)",
            "user.roles.map((role) => role.code).join(\", \")",
            "adminDataLoadedAt",
            "{children}",
        ],
    )

    require_contains(
        "frontend/src/components/layout/PublicShell.jsx",
        [
            'import { userHasRole } from "../../utils/adminState";',
            "const PUBLIC_NAV_ITEMS = [",
            "key: \"home\"",
            "key: \"catalog\"",
            "key: \"organization-info\"",
            "key: \"verify-document\"",
            "key: \"contacts\"",
            "key: \"faq\"",
            "const FOOTER_LINKS = [",
            "key: \"privacy\"",
            "key: \"offer\"",
            "function NavButton({ active, children, onClick })",
            "export function PublicShell({",
            "user,",
            "isAdmin,",
            "currentPage,",
            "onPageChange,",
            "onLogout,",
            "children,",
            "AuthenticatedUserMenu",
            "GuestAuthActions",
            "const isOrgRepresentative = userHasRole(user, \"org_rep\");",
            "onClick={() => onPageChange(\"home\")}",
            "PUBLIC_NAV_ITEMS.map((item) => (",
            "active={currentPage === item.key}",
            "onClick={() => onPageChange(item.key)}",
            "isAdmin && user ?",
            "active={currentPage === \"dashboard\"}",
            "onClick={() => onPageChange(\"dashboard\")}",
            "user && isOrgRepresentative ?",
            "active={currentPage === \"organization\"}",
            "onClick={() => onPageChange(\"organization\")}",
            "active={currentPage === \"account\"}",
            "onClick={() => onPageChange(\"account\")}",
            "active={currentPage === \"login\"}",
            "onClick={() => onPageChange(\"login\")}",
            "active={currentPage === \"register\"}",
            "onClick={() => onPageChange(\"register\")}",
            "{children}",
            "FOOTER_LINKS.map((item) => (",
            "onClick={() => onPageChange(item.key)}",
        ],
    )

    require_contains(
        "frontend/src/components/layout/AppShell.jsx",
        [
            "const ADMIN_SHELL_REQUIRED_KEYS = [",
            "const ADMIN_SHELL_COUNT_KEYS = [",
            "function getAdminShellNavigationStats",
            "function getAdminShellNavigationDiagnostics",
            "function AdminShellNavigationDiagnostics",
            "adminShellNavigationStats",
            "adminShellNavigationDiagnostics",
            "admin-shell-navigation-diagnostics",
            "admin-shell-navigation-summary",
            "admin-shell-navigation-attention",
            "Качество admin shell",
            "Критичных замечаний по admin shell и навигации не найдено.",
            "<AdminShellNavigationDiagnostics",
            "ОбрПортал",
            "Единый образовательный портал",
        ],
    )

    require_contains(
        "frontend/src/components/layout/PublicShell.jsx",
        [
            "function getPublicShellNavigationStats",
            "function getPublicShellNavigationDiagnostics",
            "function PublicShellNavigationDiagnostics",
            "publicShellNavigationStats",
            "publicShellNavigationDiagnostics",
            "public-shell-navigation-diagnostics",
            "public-shell-navigation-summary",
            "public-shell-navigation-attention",
            "Public nav:",
            "Footer links:",
            "Целевая зона:",
            "Auth: гостю доступны вход и регистрация.",
            "Admin bridge: администратору доступен переход в админку.",
            "Organization bridge: представителю организации доступен кабинет организации.",
            "Account bridge: пользователю доступен личный кабинет.",
            "<PublicShellNavigationDiagnostics",
            "ОбрПортал",
            "Единый образовательный портал",
            "const currentYear = new Date().getFullYear();",
            "© {currentYear} РЦДО. Все права защищены.",
        ],
    )

    require_contains(
        "frontend/src/App.jsx",
        [
            'import { useEffect, useState } from "react";',
            'import { Navigate } from "react-router-dom";',
            'import { AppShell } from "./components/layout/AppShell";',
            'import { PublicShell } from "./components/layout/PublicShell";',
            "EMPTY_ADMIN_DATA,",
            "getNowLabel,",
            "sortOrganizations,",
            "sortRoles,",
            "sortUsers,",
            'import { AdminNotFoundPage } from "./pages/AdminNotFoundPage";',
            'import { PublicRoutes } from "./routes/PublicRoutes";',
            'import { AdminPageRenderer } from "./routes/AdminPageRenderer";',
            'import { useAdminSelections } from "./hooks/useAdminSelections";',
            'import { useAdminEntityActions } from "./hooks/useAdminEntityActions";',
            'import { useAdminDetailActions } from "./hooks/useAdminDetailActions";',
            'import { useAdminAuditActions } from "./hooks/useAdminAuditActions";',
            'import { useSystemStatus } from "./hooks/useSystemStatus";',
            'import { useAdminDataLoader } from "./hooks/useAdminDataLoader";',
            'import { usePendingEnrollment } from "./hooks/usePendingEnrollment";',
            'import { useAuthFlow } from "./hooks/useAuthFlow";',
            'import { useAppNavigation } from "./hooks/useAppNavigation";',
            'import { usePageMeta } from "./hooks/usePageMeta";',
            'import { useAppRouteState } from "./hooks/useAppRouteState";',
            "export default function App()",
            "useSystemStatus();",
            "usePendingEnrollment({",
            "useAppNavigation({",
            "useAdminDataLoader({",
            "useAdminSelections();",
            "useAuthFlow({",
            "useAdminDetailActions({",
            "useAdminAuditActions({",
            "useAdminEntityActions({",
            "const location = usePageMeta();",
            "useEffect(() => {",
            "loadSystemStatus();",
            "bootstrapAuthState();",
            "}, []);",
            "useAppRouteState({",
            "pathname: location.pathname,",
            "const adminPageRendererProps = {",
            "locationPathname: location.pathname,",
            "handleApplyAuditFilters,",
            "const adminPageContent = isUnknownAdminRoute ?",
            "<AdminNotFoundPage",
            "<AdminPageRenderer {...adminPageRendererProps} />",
            "if (isAdminRoute)",
            "if (initializingAuth)",
            "if (!isAdmin)",
            "return <Navigate to=\"/login\" replace />;",
            "<AppShell",
            "currentPage={activeAdminPage}",
            "onPageChange={handleNavigateAdminPage}",
            "counts={{",
            "users: adminData.users.length,",
            "auditEvents: adminData.auditEvents.length,",
            "{adminPageContent}",
            "<PublicShell",
            "currentPage={currentPublicPage}",
            "onPageChange={handleNavigatePublicPage}",
            "onLogout={handleLogout}",
            "<PublicRoutes",
            "handleRegister={handleRegister}",
            "handleNavigatePublicPage={handleNavigatePublicPage}",
            "handleOpenPublicCourse={handleOpenPublicCourse}",
        ],
    )


    require_contains(
        "frontend/src/components/layout/GuestAuthActions.jsx",
        [
            "export function GuestAuthActions({",
            "publicRegistrationEnabled,",
            "onPageChange,",
            'data-testid="public-header-register-button"',
            'onClick={() => onPageChange("register")}',
            'data-testid="public-header-login-button"',
            'onClick={() => onPageChange("login")}',
        ],
    )

    require_contains(
        "frontend/src/components/layout/AuthenticatedUserMenu.jsx",
        [
            "export function AuthenticatedUserMenu({",
            "user,",
            "isAdmin,",
            "onPageChange,",
            "onLogout,",
            'userHasRole(user, "admin")',
            'userHasRole(user, "org_rep")',
            'userHasRole(user, "ministry_admin")',
            '"Администратор ведомства"',
            '"Представитель организации"',
            '"Слушатель"',
            'page: "dashboard"',
            'page: "organization"',
            'page: "ministry"',
            'page: "account"',
            'data-testid="public-header-cabinet-button"',
            'data-testid="authenticated-user-menu"',
            'aria-haspopup="menu"',
            'aria-expanded={open}',
            "document.addEventListener",
            '"pointerdown"',
            '"keydown"',
            'event.key === "Escape"',
            "Публичная часть портала",
            "Выйти",
            "onLogout();",
        ],
    )

    print("Frontend hooks/layout behavior smoke passed")


if __name__ == "__main__":
    main()
