from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def read_text(relative_path: str) -> str:
    path = ROOT / relative_path

    if not path.exists():
        raise SystemExit(f"File not found: {relative_path}")

    return path.read_text(encoding="utf-8")


def require_contains(relative_path: str, fragments: list[str]) -> None:
    text = read_text(relative_path)
    missing = [fragment for fragment in fragments if fragment not in text]

    if missing:
        print(f"{relative_path} is missing required fragments:")
        for fragment in missing:
            print(f" - {fragment}")
        raise SystemExit(1)


def require_occurs(relative_path: str, fragment: str, minimum: int) -> None:
    text = read_text(relative_path)
    count = text.count(fragment)

    if count < minimum:
        print(f"{relative_path} has too few occurrences of required fragment:")
        print(f" - fragment: {fragment}")
        print(f" - expected at least: {minimum}")
        print(f" - actual: {count}")
        raise SystemExit(1)


def main() -> None:
    require_contains(
        "frontend/src/api/client.js",
        [
            "getAdminWorklistSummary(filters = {})",
            "/api/v1/admin/worklist-summary",
            "Object.entries(filters).forEach",
            "params.set(key, value)",
        ],
    )

    require_contains(
        "frontend/src/pages/AuditPage.jsx",
        [
            "function getAuditInvestigationsStats",
            "function getAuditInvestigationsDiagnostics",
            "function AuditInvestigationsDiagnostics",
            "auditInvestigationsStats",
            "auditInvestigationsDiagnostics",
            "audit-investigations-diagnostics",
            "audit-investigations-summary",
            "audit-investigations-entities",
            "audit-investigations-attention",
            "audit-investigations-attention-count",
            "audit-investigations-links",
            "Диагностика аудита и расследований",
            "Контроль фильтров action, entity_type, entity_id, actor_user_id, лимита выдачи, критичных действий и связанных разделов",
            "Что требует внимания в аудите",
            "Выдача: включён расширенный лимит расследования на 200 событий.",
            "Actor: расследование ограничено конкретным пользователем.",
            "Риск: в выдаче есть удаление, отзыв или другие критичные действия.",
            "RBAC: в выдаче есть события ролей или прав.",
            "System: часть событий выполнена без actor_user_id.",
            "Расширенная выдача",
            "Отзывы документов",
            "<AuditInvestigationsDiagnostics",
            "getAuditInvestigationsDiagnostics({",
        ],
    )

    require_contains(
        "frontend/src/pages/GroupsPage.jsx",
        [
            "function getLearningGroupOperationsStats",
            "function getLearningGroupOperationsDiagnostics",
            "function LearningGroupOperationsDiagnostics",
            "learningGroupOperationsStats",
            "learningGroupOperationsDiagnostics",
            "learning-group-operations-diagnostics",
            "learning-group-operations-summary",
            "learning-group-operations-quality",
            "learning-group-operations-attention",
            "learning-group-operations-attention-count",
            "learning-group-operations-links",
            "Диагностика операционного центра учебных групп",
            "Контроль активных и неактивных групп, организаций, кодов, описаний, участников, назначений, документов и аудита",
            "Что требует внимания в учебных группах",
            "Статус: есть неактивные учебные группы.",
            "Организации: нет доступных организаций для создания учебных групп.",
            "Код группы: часть групп не имеет кода.",
            "Описание: часть групп не имеет описания.",
            "Активные группы",
            "Неактивные группы",
            "Проблемные назначения",
            "Проблемные документы",
            "Аудит групп",
            "<LearningGroupOperationsDiagnostics",
            "getLearningGroupOperationsDiagnostics({",
        ],
    )

    require_contains(
        "frontend/src/pages/AdminEnrollmentsPage.jsx",
        [
            "function getAdminEnrollmentOperationsStats",
            "function getAdminEnrollmentOperationsDiagnostics",
            "function AdminEnrollmentOperationsDiagnostics",
            "adminEnrollmentOperationsStats",
            "adminEnrollmentOperationsDiagnostics",
            "admin-enrollment-operations-diagnostics",
            "admin-enrollment-operations-summary",
            "admin-enrollment-operations-relations",
            "admin-enrollment-operations-attention",
            "admin-enrollment-operations-attention-count",
            "admin-enrollment-operations-links",
            "Диагностика административных назначений обучения",
            "Контроль статусов assigned/active/completed, action_required, групповых назначений, связей с пользователем, организацией, группой, курсом и итоговыми документами",
            "Что требует внимания в административных назначениях",
            "Старт обучения: есть назначения в статусе assigned.",
            "Контроль: есть назначения в режиме action_required.",
            "Организация: часть назначений не привязана к организации.",
            "Группа: часть назначений не привязана к учебной группе.",
            "Массовое назначение: выполняется назначение учебной группе.",
            "Назначенные",
            "В обучении",
            "Завершённые",
            "Требуют действия",
            "Активные курсы",
            "Группы обучения",
            "Черновики документов",
            "Аудит назначений",
            "<AdminEnrollmentOperationsDiagnostics",
            "getAdminEnrollmentOperationsDiagnostics({",
        ],
    )

    require_contains(
        "frontend/src/pages/AdminCoursesPage.jsx",
        [
            "function getAdminCourseCatalogStats",
            "function getAdminCourseCatalogDiagnostics",
            "function AdminCourseCatalogDiagnostics",
            "adminCourseCatalogStats",
            "adminCourseCatalogDiagnostics",
            "admin-course-catalog-diagnostics",
            "admin-course-catalog-summary",
            "admin-course-catalog-structure",
            "admin-course-catalog-attention",
            "admin-course-catalog-attention-count",
            "admin-course-catalog-links",
            "Диагностика административного каталога курсов",
            "Контроль активности, структуры модулей и уроков, обязательных материалов, публичного каталога, назначений и итоговых документов",
            "Что требует внимания в административном каталоге курсов",
            "Структура: есть курсы без модулей.",
            "Структура: есть модули без уроков.",
            "Прохождение: в текущей выборке нет обязательных уроков.",
            "Публичный каталог: часть курсов не имеет slug",
            "Итоговые документы: у части курсов не указан тип итогового документа.",
            "Активные курсы",
            "Неактивные курсы",
            "Публичный каталог",
            "Активное обучение",
            "Завершённое обучение",
            "Черновики документов",
            "Аудит курсов",
            'data-testid="admin-courses-structure-tree"',
            "getAdminCourseCatalogDiagnostics({",
        ],
    )

    require_contains(
        "frontend/src/pages/DocumentsPage.jsx",
        [
            "documents_user_id: filters.user_id",
            "documents_enrollment_id: filters.enrollment_id",
            "documents_document_type: filters.document_type",
            "documents_q: filters.q",
            "getAdminWorklistSummary({",
        ],
    )

    require_contains(
        "frontend/src/pages/AdminEnrollmentsPage.jsx",
        [
            "enrollments_user_id: activeFilters.user_id",
            "enrollments_course_id: activeFilters.course_id",
            "enrollments_organization_id: activeFilters.organization_id",
            "enrollments_learning_group_id: activeFilters.learning_group_id",
            "enrollments_q: activeFilters.q",
            "getEnrollmentAttentionItems",
            "enrollment-attention-fields",
            "enrollment-attention-count",
            "enrollment-attention-diagnostics-note",
            "Что требует внимания в назначении",
            "Диагностика основана на статусе, датах, группе, организации и PDF-профиле организации.",
            "Старт обучения: назначение ещё не переведено в работу.",
            "Дата старта: не заполнена, проверьте фактическое начало обучения.",
            "Итоговый документ: завершённое обучение нужно проверить в реестре документов.",
            "Дата завершения: не заполнена, проверьте корректность статуса.",
            "Организация: не указана, PDF будет использовать fallback-настройки приложения.",
            "PDF-профиль организации: не заполнено полей",
            "Группа: назначение без учебной группы, проверьте контекст группового обучения.",
            "const enrollmentAttentionItems = getEnrollmentAttentionItems(",
            "enrollmentProfileStatus.toneClass",
            "enrollmentProfileStatus.label",
        ],
    )

    documents_text = read_text("frontend/src/pages/DocumentsPage.jsx")
    forbidden_documents_counter_fragments = [
        "getAdminDocuments(counterFilters)",
        "getAdminDocuments(actionRequiredCounterFilters)",
    ]

    for fragment in forbidden_documents_counter_fragments:
        if fragment in documents_text:
            raise SystemExit(
                f"frontend/src/pages/DocumentsPage.jsx still loads counter list: {fragment}"
            )

    enrollments_text = read_text("frontend/src/pages/AdminEnrollmentsPage.jsx")
    forbidden_enrollments_counter_fragments = [
        "getAdminEnrollments(countFilters)",
        "getAdminEnrollments(actionRequiredCountFilters)",
    ]

    for fragment in forbidden_enrollments_counter_fragments:
        if fragment in enrollments_text:
            raise SystemExit(
                f"frontend/src/pages/AdminEnrollmentsPage.jsx still loads counter list: {fragment}"
            )

    forbidden_dead_counter_helpers = [
        ("frontend/src/pages/DocumentsPage.jsx", "function calculateDocumentStatusCounts"),
        ("frontend/src/pages/AdminEnrollmentsPage.jsx", "function calculateStatusCounts"),
    ]

    for relative_path, fragment in forbidden_dead_counter_helpers:
        if fragment in read_text(relative_path):
            raise SystemExit(f"{relative_path} still contains dead counter helper: {fragment}")

    require_contains(
        "frontend/src/pages/DocumentsPage.jsx",
        [
            "getDocumentActionRequiredHint",
            "document-action-required-hint",
            "document-attention-fields",
            "getDocumentAttentionItems",
            "getDocumentAttentionTone",
            "documentAttentionTone.panelClass",
            "documentAttentionTone.badgeClass",
            "bg-red-50 text-red-800 ring-red-200",
            "bg-amber-50 text-amber-900 ring-amber-200",
            "Что требует внимания",
            "document-attention-count",
            "Пунктов внимания:",
            "documentAttentionItems.length",
            "Публикация: черновик нужно доработать или опубликовать.",
            "Файл: опубликованный документ недоступен для скачивания.",
            "document-action-required-primary-action",
            "documents-action-required-banner",
            "documents-worklist-summary-note",
            "Счётчики быстрых фильтров рассчитаны по текущим фильтрам страницы.",
            "Включён режим контроля документов",
            "Показать все документы",
            "Доработать документ",
            "Загрузить файл",
            "Связанное назначение",
            "Документы назначения",
            "enrollment_id: documentItem.enrollment_id",
            "user_id: documentItem.user_id || \"\"",
            "course_id: documentItem.course_id || \"\"",
            "Требуется публикация или доработка черновика",
            "Требуется файл для опубликованного документа",
            "getAdminWorklistSummary",
            "documentsSummary.total",
            "documentsSummary.action_required",
        ],
    )

    require_contains(
        "frontend/src/pages/AdminEnrollmentsPage.jsx",
        [
            "getEnrollmentActionRequiredHint",
            "enrollment-action-required-hint",
            "enrollment-action-required-primary-action",
            "enrollment-action-required-documents-link",
            "enrollments-action-required-banner",
            "enrollments-worklist-summary-note",
            "Счётчики быстрых фильтров рассчитаны по текущим фильтрам страницы.",
            "Включён режим контроля назначений",
            "Показать все назначения",
            "Проверить назначение",
            "Открыть документы",
            "action_required: \"true\",",
            "Назначение ожидает старта обучения",
            "Завершённое обучение ожидает документ",
            "Назначения, требующие действия, не найдены",
            "getAdminWorklistSummary",
            "enrollmentsSummary.total",
            "enrollmentsSummary.action_required",
            "DOCUMENT_PROFILE_FIELDS",
            "getOrganizationDocumentProfileStatus",
            "OrganizationDocumentProfileHint",
            "enrollment-create-document-profile-hint",
            "enrollment-edit-document-profile-hint",
            "enrollment-list-document-profile-status",
            "enrollment-organization-link",
            "buildOrganizationsPath({ organization_id: enrollment.organization_id })",
            "filterOrganizationId",
            "setFilterOrganizationId",
            "Все организации",
            "organization_id: overrides.organization_id",
            "PDF: профиль организации заполнен",
            "PDF: профиль организации заполнен частично",
            "PDF: настройки приложения",
            "Итоговый PDF возьмёт реквизиты",
            "fallback-настроек приложения",
        ],
    )

    require_contains(
        "frontend/src/pages/DocumentsPage.jsx",
        [
            "function getAdminDocumentRegistryStats",
            "function getAdminDocumentRegistryDiagnostics",
            "function AdminDocumentRegistryDiagnostics",
            "adminDocumentRegistryStats",
            "adminDocumentRegistryDiagnostics",
            "admin-document-registry-diagnostics",
            "admin-document-registry-summary",
            "admin-document-registry-quality",
            "admin-document-registry-attention",
            "admin-document-registry-attention-count",
            "admin-document-registry-links",
            "Диагностика административного реестра документов",
            "Контроль фильтров, статусов, файлов, PDF, публикации, отзыва, восстановления и action_required",
            "Что требует внимания в административном реестре",
            "Публикация: есть черновики документов",
            "Отзыв: есть отозванные документы",
            "Контроль: есть документы в режиме action_required.",
            "Регенерация PDF: выполняется пересборка итогового документа.",
            "Черновики",
            "Опубликованные",
            "Отозванные",
            "Требуют действия",
            "Завершённые назначения",
            "<AdminDocumentRegistryDiagnostics",
            "getAdminDocumentRegistryDiagnostics({",
        ],
    )

    require_contains(
        "frontend/src/pages/VerifyDocumentPage.jsx",
        [
            "function getPublicVerificationSourceStats",
            "function PublicVerificationQrOperationsPanel",
            "verificationSourceStats",
            "public-verification-qr-operations-panel",
            "public-verification-qr-status",
            "public-verification-qr-summary",
            "public-verification-qr-attention",
            "public-verification-qr-links",
            "Операционный контроль QR",
            "Проверка по номеру, коду и QR-ссылке",
            "Контрольные правила публичной проверки",
            "Опубликованный документ подтверждается публичным реестром.",
            "Черновик не должен подтверждаться публичной проверкой.",
            "Отозванный документ показывается как недействующий.",
            "QR-ссылка считается готовой",
            "Публичная страница не раскрывает файл документа",
            "Личный кабинет",
            "Каталог курсов",
            "Контакты организации",
            "<PublicVerificationQrOperationsPanel",
            "getPublicVerificationSourceStats({",
        ],
    )

    require_contains(
        "frontend/src/pages/AccountPage.jsx",
        [
            "function getCompletionDocumentStats",
            "function getCompletionDocumentDiagnostics",
            "function CompletionDocumentsDiagnostics",
            "completionDocumentStats",
            "completionDocumentDiagnostics",
            "account-completion-documents-diagnostics",
            "account-completion-documents-summary",
            "account-completion-documents-quality",
            "account-completion-documents-attention",
            "account-completion-documents-attention-count",
            "account-completion-documents-links",
            "Контроль итоговых документов",
            "Диагностика черновиков, публикации, скачивания, QR/публичной проверки, отзыва и восстановления документов",
            "Что требует внимания в итоговых документах",
            "Публикация: есть черновики итоговых документов",
            "Публичная проверка: есть документы с номером или кодом проверки.",
            "Скачивание: часть опубликованных документов недоступна для скачивания.",
            "Отзыв: есть отозванные итоговые документы",
            "Перейти к моим документам",
            "Перейти к завершённым программам",
            "Публичная проверка",
            "<CompletionDocumentsDiagnostics",
            "getCompletionDocumentDiagnostics({",
        ],
    )

    require_contains(
        "frontend/src/pages/AccountPage.jsx",
        [
            "function getLearningProgressStats",
            "function getLearningProgressDiagnostics",
            "function LearningProgressDiagnostics",
            "learningProgressStats",
            "learningProgressDiagnostics",
            "account-learning-progress-diagnostics",
            "account-learning-progress-summary",
            "account-learning-progress-opened-course",
            "account-learning-progress-attention",
            "account-learning-progress-attention-count",
            "account-learning-progress-links",
            "Контроль прохождения обучения",
            "Диагностика прогресса, обязательных уроков, завершения курса и итоговых документов",
            "Что требует внимания в прохождении обучения",
            "Старт обучения: есть назначенные программы",
            "Уроки: откройте программу активного курса",
            "Завершение: обязательные уроки пройдены не полностью",
            "Итоговый документ: есть черновики документов",
            "Перейти к программам",
            "Перейти к документам",
            "Открыть каталог",
            "Проверить документ",
            "<LearningProgressDiagnostics",
            "getLearningProgressDiagnostics({",
        ],
    )

    require_contains(
        "frontend/src/pages/CourseDetailPage.jsx",
        [
            "function getCourseStructureStats",
            "function getCourseDetailDiagnostics",
            "function CourseSelfEnrollmentDiagnostics",
            "courseDiagnostics",
            "course-self-enrollment-diagnostics",
            "course-self-enrollment-status",
            "course-self-enrollment-summary",
            "course-self-enrollment-attention",
            "course-self-enrollment-attention-count",
            "course-self-enrollment-links",
            "Диагностика карточки курса",
            "Карточка курса и самозапись",
            "Что требует внимания в карточке курса",
            "Карточка: курс не выбран или не найден.",
            "Структура: у курса пока нет опубликованных модулей.",
            "Самозапись: пользователь не авторизован",
            "Самозапись: пользователь авторизован и может записаться на программу.",
            "Назначение: обучение уже идёт",
            "Вернуться в каталог",
            "Личный кабинет",
            "Проверить документ",
            "<CourseSelfEnrollmentDiagnostics",
            "getCourseDetailDiagnostics({",
        ],
    )

    require_contains(
        "frontend/src/pages/CatalogPage.jsx",
        [
            "function getCatalogDiagnostics",
            "function CatalogDiagnostics",
            "catalogDiagnostics",
            "catalog-public-diagnostics",
            "catalog-public-status",
            "catalog-public-summary",
            "catalog-public-filters",
            "catalog-public-attention",
            "catalog-public-attention-count",
            "catalog-public-links",
            "Диагностика каталога",
            "Публичный каталог и самозапись",
            "Что требует внимания в каталоге",
            "Каталог: список публичных программ загружается.",
            "Каталог: не удалось загрузить публичные программы",
            "Поиск: применён текстовый фильтр",
            "Формат: применён фильтр по формату обучения.",
            "Самозапись: пользователь не авторизован",
            "Личный кабинет",
            "Проверить документ",
            "<CatalogDiagnostics",
            "getCatalogDiagnostics({",
        ],
    )

    require_contains(
        "frontend/src/pages/VerifyDocumentPage.jsx",
        [
            "function getPublicVerificationDiagnostics",
            "function PublicVerificationDiagnostics",
            "verificationDiagnostics",
            "public-verification-diagnostics",
            "public-verification-status",
            "public-verification-summary",
            "public-verification-attention",
            "public-verification-attention-count",
            "Диагностика проверки",
            "Публичная проверка документа",
            "Что показывает проверка",
            "Запрос: номер документа или код проверки ещё не введён.",
            "Запрос: значение введено, нажмите кнопку проверки.",
            "Проверка: выполняется запрос к публичному реестру.",
            "Реестр: документ по введённому номеру или коду проверки не найден.",
            "Статус: документ опубликован и подтверждается публичным реестром.",
            "Статус: документ отозван, его нельзя считать действующим.",
            "QR/код: код проверки доступен, можно использовать публичную ссылку и QR-код.",
            "getPublicVerificationDiagnostics({",
            "<PublicVerificationDiagnostics",
        ],
    )

    require_contains(
        "frontend/src/pages/AccountPage.jsx",
        [
            "function getAccountAttentionItems",
            "function AccountAccessDiagnostics",
            "accountAttentionItems",
            "account-access-diagnostics",
            "account-access-summary",
            "account-access-attention",
            "account-access-attention-count",
            "account-access-links",
            "Контроль доступа и документов",
            "Диагностика личного кабинета, обучения, документов, скачивания и публичной проверки",
            "Что требует внимания в личном кабинете",
            "Профиль: не указан e-mail",
            "Обучение: нет назначенных программ",
            "Документы: есть черновики",
            "Документы: есть отозванные документы",
            "Документы: есть записи без файла",
            "Публичная проверка: опубликованные документы без номера или кода проверки",
            "Критичных замечаний по доступу, обучению и документам не найдено.",
            "Открыть каталог курсов",
            "Перейти к программам",
            "Перейти к моим документам",
            "id=\"account-courses\"",
            "id=\"account-documents\"",
            "getAccountAttentionItems(profile, courses, documents)",
            "documentStatusCounts.available",
        ],
    )

    require_contains(
        "frontend/src/hooks/useAdminDataLoader.js",
        [
            "getAdminDashboardSummary,",
            "getAdminDashboardSummary()",
            "dashboardSummary",
        ],
    )

    loader_text = read_text("frontend/src/hooks/useAdminDataLoader.js")
    forbidden_loader_fragments = [
        "getAdminCourses({ limit: 300 })",
        "getAdminEnrollments({ limit: 300 })",
        "getAdminDocuments({ limit: 300 })",
    ]

    for fragment in forbidden_loader_fragments:
        if fragment in loader_text:
            raise SystemExit(
                f"frontend/src/hooks/useAdminDataLoader.js still loads large Dashboard list: {fragment}"
            )

    documents_text = read_text("frontend/src/pages/DocumentsPage.jsx")
    forbidden_documents_counter_fragments = [
        "getAdminDocuments(counterFilters)",
        "getAdminDocuments(actionRequiredCounterFilters)",
    ]

    for fragment in forbidden_documents_counter_fragments:
        if fragment in documents_text:
            raise SystemExit(
                f"frontend/src/pages/DocumentsPage.jsx still loads counter list: {fragment}"
            )

    enrollments_text = read_text("frontend/src/pages/AdminEnrollmentsPage.jsx")
    forbidden_enrollments_counter_fragments = [
        "getAdminEnrollments(countFilters)",
        "getAdminEnrollments(actionRequiredCountFilters)",
    ]

    for fragment in forbidden_enrollments_counter_fragments:
        if fragment in enrollments_text:
            raise SystemExit(
                f"frontend/src/pages/AdminEnrollmentsPage.jsx still loads counter list: {fragment}"
            )

    require_contains(
        "frontend/src/pages/DashboardPage.jsx",
        [
            "export function DashboardPage({",
            "email,",
            "password,",
            "loading,",
            "adminLoading,",
            "error,",
            "user,",
            "rbac,",
            "adminData,",
            "dashboardSummary",
            "summaryNumber",
            "usersTotalCount",
            "documentsTotalCount",
            "priorityActions",
            "urgentPriorityActions",
            "displayedPriorityActions",
            "DashboardTaskCard",
            "dashboardTaskCards",
            "function WorkflowCard({ title, description, links, testId })",
            "data-testid={testId}",
            "dashboard-organization-document-flow",
            "dashboard-document-quality-flow",
            "Организации → группы → назначения → документы",
            "Контроль полного организационного контура",
            "buildEnrollmentsPath()",
            "buildDocumentsPath()",
            "Назначения требуют действия",
            "Документы требуют действия",
            "Контроль качества реестра",
            "Аудит документов",
            "Регенерация PDF",
            "buildAuditPath({ entity_type: \"document\" })",
            "buildAuditPath({ action: \"admin.document_regenerated\" })",
            "totalDashboardTasksCount",
            "dashboardTasksStatusText",
            "dashboard-work-tasks-status",
            "Есть рабочие задачи:",
            "Все рабочие задачи закрыты.",
            "Всего задач:",
            "dashboard-work-tasks",
            "dashboard-documents-task",
            "dashboard-enrollments-task",
            "testId={task.testId}",
            "Рабочие задачи",
            "Главные действия администратора по документам и назначениям.",
            "Разобрать документы",
            "Разобрать назначения",
            "WorkCenterActionCard",
            "Рабочий центр администратора",
            "adminDataLoadedAt,",
            "onEmailChange,",
            "onPasswordChange,",
            "onLogin,",
            "onLogout,",
            "onRbacCheck,",
            "onRefreshAdminData,",
            "SectionCard",
            "onRefreshAdminData",
            "actionRequiredEnrollmentsCount",
            "actionRequiredDocumentsCount",
            "Назначения требуют действия",
            "Документы требуют действия",
            "buildEnrollmentsPath({ action_required: \"true\" })",
            "buildDocumentsPath({ action_required: \"true\" })",
            "onRbacCheck",
            "onLogout",
            "dashboard-enrollment-operations-flow",
            "Операционный центр назначений",
            "Старт, завершение, выпуск документов и аудит назначений",
            "Документы по проблемным назначениям",
            "Аудит назначений",
            "buildAuditPath({ entity_type: \"enrollment\" })",
            "buildEnrollmentsPath({ status: \"assigned\" })",
            "buildEnrollmentsPath({ status: \"active\" })",
            "buildEnrollmentsPath({ status: \"completed\" })",
            "dashboard-organization-operations-flow",
            "Операционный центр организаций",
            "Контроль организаций, групп, проблемных назначений, документов и аудита организационного контура.",
            "Все организации",
            "Организации с КПП",
            "Группы организаций",
            "Назначения организаций",
            "Проблемные назначения",
            "Проблемные документы",
            "Аудит организаций",
            "buildOrganizationsPath({ scope: \"with_kpp\" })",
            "buildAuditPath({ entity_type: \"organization\" })",
            "dashboard-group-operations-flow",
            "Операционный центр групп",
            "Контроль учебных групп, активности, участников, назначений и связанных документов.",
            "Все группы",
            "Активные группы",
            "Неактивные группы",
            "Организации групп",
            "Назначения по группам",
            "buildGroupsPath({ status: \"active\" })",
            "buildGroupsPath({ status: \"inactive\" })",
            "dashboard-user-operations-flow",
            "Операционный центр пользователей",
            "Контроль активности, ролей, назначений, документов и аудита действий по пользователям.",
            "Все пользователи",
            "Активные пользователи",
            "Неактивные пользователи",
            "Роли пользователей",
            "Назначения пользователей",
            "Документы пользователей",
            "Аудит пользователей",
            "buildUsersPath({ activity: \"active\" })",
            "buildUsersPath({ activity: \"inactive\" })",
            "buildAuditPath({ entity_type: \"user\" })",
            "dashboard-rbac-operations-flow",
            "Операционный центр ролей и прав",
            "Контроль системных и пользовательских ролей, permissions, назначений ролей и аудита RBAC-действий.",
            "Все роли",
            "Admin-роли",
            "Все права",
            "Audit-права",
            "Пользователи с ролью admin",
            "Аудит ролей",
            "Аудит прав",
            "buildRolesPath({ q: \"admin\" })",
            "buildPermissionsPath({ group: \"audit\" })",
            "buildUsersPath({ role: \"admin\" })",
            "buildAuditPath({ entity_type: \"role\" })",
            "buildAuditPath({ entity_type: \"permission\" })",
            "dashboard-audit-investigations-flow",
            "Операционный центр аудита и расследований",
            "Расследование действий по пользователям, документам, назначениям, организациям, ролям и permissions.",
            "Последние 25 событий",
            "Последние 200 событий",
            "Аудит permissions",
            "buildAuditPath({ limit: \"25\" })",
            "buildAuditPath({ limit: \"200\" })",
            "buildAuditPath({ action: \"admin.user_created\" })",
            "dashboard-account-access-flow",
            "Операционный центр личного кабинета",
            "Контроль пользовательского доступа к кабинету, обучению, документам, скачиванию и публичной проверке.",
            "Личный кабинет",
            "Каталог курсов",
            "Публичная проверка документа",
            "Активные назначения",
            "Завершённые назначения",
            "Документы пользователя",
            "Черновики документов",
            "Отозванные документы",
            "to: \"/account\"",
            "to: \"/catalog\"",
            "to: \"/verify-document\"",
            "buildDocumentsPath({ status: \"available\" })",
            "buildDocumentsPath({ status: \"draft\" })",
            "buildDocumentsPath({ status: \"revoked\" })",
            "dashboard-public-verification-flow",
            "Операционный центр публичной проверки документов",
            "Контроль публичной проверки по номеру/коду, QR-ссылок, статусов документов и ошибок верификации.",
            "Публичная проверка",
            "Доступные документы",
            "Черновики не проверяются",
            "Отзыв документов",
            "Восстановление документов",
            "buildAuditPath({ action: \"admin.document_revoked\" })",
            "buildAuditPath({ action: \"admin.document_restored\" })",
            "dashboard-public-catalog-flow",
            "Операционный центр каталога и публичных курсов",
            "Контроль публичного каталога, карточек курсов, самозаписи, активных программ, назначений и итоговых документов.",
            "Публичный каталог",
            "Неактивные курсы",
            "Все назначения",
            "Документы выпускников",
            "Публичная проверка документов",
            "Аудит курсов",
            "buildCoursesPath({ is_active: \"true\" })",
            "buildCoursesPath({ is_active: \"false\" })",
            "buildAuditPath({ entity_type: \"course\" })",
            "dashboard-course-self-enrollment-flow",
            "Операционный центр карточки курса и самозаписи",
            "Контроль публичной карточки курса, структуры модулей/уроков, самозаписи, существующих назначений и ошибок записи.",
            "Каталог для выбора курса",
            "Проверка отсутствующей карточки",
            "Назначены",
            "to: \"/courses/SMOKE-NOT-FOUND\"",
            "dashboard-learning-progress-flow",
            "Операционный центр прохождения обучения и уроков",
            "Контроль личного кабинета обучения, прогресса, обязательных уроков, завершения курса и черновика итогового документа.",
            "Личный кабинет обучения",
            "Назначенные программы",
            "Обучение в процессе",
            "Завершённое обучение",
            "Черновики итоговых документов",
            "Опубликованные итоговые документы",
            "dashboard-completion-documents-flow",
            "Операционный центр итоговых документов после обучения",
            "Контроль черновиков после завершения курса, публикации, скачивания PDF, QR-проверки, отзыва, восстановления и аудита документов.",
            "Опубликованные документы",
            "Личный кабинет слушателя",
            "dashboard-public-verification-qr-flow",
            "Операционный центр публичной проверки и QR-документов",
            "Контроль проверки по номеру и коду, QR-ссылок, статусов available/revoked/draft, ошибок поиска и аудита операций с документами.",
            "Проверка по номеру",
            "Проверка по коду",
            "to: \"/verify-document?number=SMOKE-NOT-FOUND\"",
            "to: \"/verify-document?code=SMOKE-NOT-FOUND\"",
            "dashboard-admin-document-registry-flow",
            "Операционный центр административного реестра документов",
            "Контроль фильтров реестра, черновиков, опубликованных и отозванных документов, action_required, типов документов, скачивания, публикации, отзыва, восстановления и регенерации PDF.",
            "Реестр документов",
            "Черновики к публикации",
            "Сертификаты",
            "Документы завершённых назначений",
            "Создание документов",
            "buildDocumentsPath({ document_type: \"certificate\" })",
            "buildAuditPath({ action: \"admin.document_created\" })",
            "dashboard-admin-course-catalog-flow",
            "Операционный центр административного каталога курсов",
            "Контроль активных и неактивных курсов, модулей, уроков, обязательных материалов, самозаписи, назначений, завершений и итоговых документов.",
            "Реестр курсов",
            "Активные курсы",
            "Самозапись слушателей",
            "Активное обучение",
            "Итоговые документы",
            "buildCoursesPath()",
            "dashboard-admin-enrollment-operations-flow",
            "Операционный центр административных назначений обучения",
            "Контроль назначений assigned/active/completed, action_required, групповых назначений, связей с пользователем, организацией, группой и курсом, завершения обучения и итоговых документов.",
            "Реестр назначений",
            "Назначенные",
            "В обучении",
            "Завершённые",
            "Курсы для назначений",
            "Группы обучения",
            "Пользователи",
            "Организации",
            "to: \"/admin/groups\"",
            "to: \"/admin/users\"",
            "to: \"/admin/organizations\"",
            "dashboard-learning-group-operations-flow",
            "Операционный центр учебных групп",
            "Контроль активных и неактивных учебных групп, организаций, участников, групповых назначений, action_required, документов и аудита связей обучения.",
            "Реестр групп",
            "Пользователи групп",
            "Аудит групп",
            "buildGroupsPath()",
            "buildGroupsPath({ active: \"true\" })",
            "buildGroupsPath({ active: \"false\" })",
            "buildOrganizationsPath()",
            "buildUsersPath()",
            "buildAuditPath({ entity_type: \"learning_group\" })",
            "Контроль журнала событий, фильтров по действиям, сущностям, актору, лимиту выдачи и быстрых расследований по пользователям, организациям, группам, назначениям, документам, ролям и правам.",
            "Журнал аудита",
            "Расширенный лимит",
            "Фильтр по актору",
            "Создание пользователей",
            "Регенерация документов",
            "buildAuditPath()",
            "buildAuditPath({ actor_user_id: \"00000000-0000-0000-0000-000000000000\" })",
            "dashboard-frontend-shell-navigation-flow",
            "Операционный центр качества frontend shell и навигации",
            "Контроль admin/public shell, прямых маршрутов, fallback-страниц, ссылок Dashboard, публичных страниц, навигационных builders и защиты от сломанных переходов.",
            "Admin shell",
            "Неизвестный admin route",
            "Группы",
            "Курсы",
            "Назначения",
            "Документы",
            "Аудит",
            "Публичная главная",
            "Каталог",
            "Проверка документа",
            "Кабинет организации",
            "Вход",
            "Регистрация",
            "to: \"/admin\"",
            "to: \"/admin/__missing_shell_route__\"",
            "to: \"/admin/courses\"",
            "to: \"/admin/enrollments\"",
            "to: \"/admin/documents\"",
            "to: \"/admin/audit-events\"",
            "to: \"/\"",
            "to: \"/organization\"",
            "to: \"/login\"",
            "to: \"/register\"",
            "dashboard-frontend-routes-builders-meta-flow",
            "Операционный центр качества frontend routes/builders/meta",
            "Контроль adminRoutes, adminLinks, publicRoutes, meta-описаний, query builders, entity links, unknown/fallback routes и соответствия routes → links → pages → meta.",
            "Admin route registry",
            "Users builder",
            "Organizations builder",
            "Groups builder",
            "Courses builder",
            "Enrollments builder",
            "Documents builder",
            "Roles builder",
            "Permissions builder",
            "Audit builder",
            "Public home meta",
            "Public catalog meta",
            "Public course fallback meta",
            "Organization info meta",
            "Verify document meta",
            "Verify code fallback",
            "Public contacts meta",
            "Public not found meta",
            "buildGroupsPath({ status: \"active\", organization_id: \"00000000-0000-0000-0000-000000000000\" })",
            "buildCoursesPath({ is_active: \"true\", q: \"__missing_routes_meta_course__\" })",
            "buildEnrollmentsPath({ status: \"completed\", action_required: \"true\" })",
            "buildDocumentsPath({ status: \"available\", type: \"certificate\" })",
            "buildRolesPath({ type: \"system\" })",
            "buildAuditPath({ entity_type: \"document\", limit: \"25\" })",
            "to: \"/courses/__missing_routes_meta_course__\"",
            "to: \"/organization-info\"",
            "to: \"/verify/__missing_routes_meta_code__\"",
            "to: \"/contacts\"",
            "to: \"/__missing_routes_meta_public__\"",
            "dashboard-frontend-smoke-guards-coverage-flow",
            "Операционный центр качества frontend smoke/guards coverage",
            "Контроль smoke/guard scripts, покрытия frontend/backend проверками, API error guard, mojibake guard, BOM/text encoding guard, bundle encoding и защиты от маркеров незавершённой реализации.",
            "Frontend coverage guard",
            "Backend coverage guard",
            "Frontend API error guard",
            "Mojibake guard",
            "Source BOM guard",
            "Text encoding guard",
            "Admin pages smoke",
            "Public pages smoke",
            "Account page smoke",
            "Hooks/layout smoke",
            "Utils/routes smoke",
            "Documents smoke",
            "Implementation markers guard",
            "Bundle encoding guard",
            "dashboard-ci-local-gate-flow",
            "Операционный центр качества CI/CD и локального gate",
            "Контроль соответствия GitHub Actions и локального полного gate: secret scan, encoding guards, frontend guards, pytest, smoke scripts, coverage guards, frontend build, bundle encoding и синхронизация develop/main.",
            "CI workflow",
            "Secret scan",
            "Encoding guards",
            "Frontend guards",
            "Backend pytest",
            "Auth RBAC smoke",
            "Account smoke",
            "Frontend core smoke",
            "Frontend coverage",
            "Backend coverage",
            "Frontend build",
            "Bundle encoding",
            "Branch sync",
            "to: \"/admin?from=ci-local-gate\"",
            "to: \"/admin/audit-events?entity_type=document&limit=25\"",
            "to: \"/catalog?from=ci-local-gate\"",
            "to: \"/admin/audit-events?entity_type=user&limit=25\"",
            "to: \"/admin/users?activity=inactive&from=ci-local-gate\"",
            "to: \"/contacts?from=ci-local-gate\"",
            "to: \"/account?from=ci-local-gate\"",
            "to: \"/organization-info?from=ci-local-gate\"",
            "to: \"/admin?from=frontend-coverage\"",
            "to: \"/admin/__missing_ci_gate_route__\"",
            "to: \"/verify-document?from=ci-local-gate\"",
            "to: \"/__missing_ci_gate_public__\"",
            "dashboard-production-readiness-release-flow",
            "Операционный центр production readiness / release checklist",
            "Контроль готовности релиза: env/config, Docker Compose, health/ready, migrations, seeds, storage, logs, rollback-порядок, CI/local gate, smoke-команды и release checklist.",
            "Env/config readiness",
            "Docker Compose readiness",
            "Health and ready endpoints",
            "Migrations and seeds",
            "Storage readiness",
            "Logs and failure diagnostics",
            "Release smoke commands",
            "Public verification readiness",
            "Account readiness",
            "Organization readiness",
            "Admin registry readiness",
            "Rollback order",
            "CI/local gate release check",
            "Release checklist fallback",
            "to: \"/admin?from=production-readiness\"",
            "to: \"/admin/__missing_release_route__\"",
            "to: \"/catalog?from=production-readiness\"",
            "to: \"/verify-document?from=production-readiness\"",
            "to: \"/account?from=production-readiness\"",
            "to: \"/organization-info?from=production-readiness\"",
            "to: \"/admin/documents?action_required=true&from=production-readiness\"",
            "to: \"/admin/audit-events?entity_type=organization&limit=25\"",
            "to: \"/__missing_release_public__\"",
            "dashboard-release-versioning-handoff-flow",
            "Операционный центр release versioning / changelog / deployment handoff",
            "Контроль управляемого релиза: версия backend/frontend, changelog, release notes, tag-порядок, deployment handoff, rollback-команды, release checklist и post-release verification.",
            "Version source",
            "Backend health version",
            "Frontend package version",
            "Changelog readiness",
            "Release notes",
            "Tag order",
            "Deployment handoff",
            "Rollback commands",
            "Release checklist",
            "CI/local gate",
            "Public verification",
            "Account verification",
            "Release fallback",
            "to: \"/admin?from=release-versioning\"",
            "to: \"/catalog?from=release-versioning\"",
            "to: \"/admin/documents?status=available&type=certificate&from=release-versioning\"",
            "to: \"/admin/__missing_release_version_route__\"",
            "to: \"/organization-info?from=release-versioning\"",
            "to: \"/verify-document?from=release-versioning\"",
            "to: \"/account?from=release-versioning\"",
            "to: \"/__missing_release_version_public__\"",
            "dashboard-release-candidate-tag-readiness-flow",
            "Операционный центр release candidate / tag readiness / post-release verification",
            "Контроль release candidate перед тегом: git tag readiness, версия, changelog, handoff, CI status, production readiness, smoke-проверки, post-release verification и rollback-порядок.",
            "Release candidate source",
            "Tag readiness",
            "Versioning guard",
            "Changelog verification",
            "CI status readiness",
            "Production readiness",
            "Health/ready verification",
            "Public catalog verification",
            "Public document verification",
            "Admin documents verification",
            "Rollback verification",
            "Release candidate fallback",
            "to: \"/admin?from=release-candidate\"",
            "to: \"/admin/__missing_release_candidate_route__\"",
            "to: \"/organization-info?from=release-candidate\"",
            "to: \"/catalog?from=release-candidate\"",
            "to: \"/verify-document?from=release-candidate\"",
            "to: \"/account?from=release-candidate\"",
            "to: \"/admin/documents?action_required=true&from=release-candidate\"",
            "to: \"/__missing_release_candidate_public__\"",
            "dashboard-release-tag-publication-smoke-flow",
            "Операционный центр release tag / final publication / post-release smoke",
            "Контроль финальной публикации релиза: annotated tag, release notes, final publication order, post-release smoke, health/ready, public/admin/account/document verification и rollback checkpoint.",
            "Release tag source",
            "Final tag readiness",
            "Release candidate readiness",
            "Versioning handoff",
            "Post-release health",
            "Post-release catalog",
            "Post-release public verification",
            "Post-release account",
            "Admin documents smoke",
            "Rollback checkpoint",
            "Release tag fallback",
            "to: \"/admin?from=release-tag\"",
            "to: \"/admin/__missing_release_tag_route__\"",
            "to: \"/admin/documents?status=available&type=certificate&from=release-tag\"",
            "to: \"/catalog?from=release-tag\"",
            "to: \"/verify-document?from=release-tag\"",
            "to: \"/account?from=release-tag\"",
            "to: \"/admin/documents?action_required=true&from=release-tag\"",
            "to: \"/__missing_release_tag_public__\"",
        ],
    )

    require_contains(
        "frontend/src/pages/UsersPage.jsx",
        [
            "export function UsersPage({",
            "user,",
            "users,",
            "roles,",
            "organizations,",
            "loading,",
            "selectedUser,",
            "selectedUserLoading,",
            "selectedUserError,",
            "onOpenUser,",
            "onCloseUser,",
            "onCreateUser,",
            "onUpdateUser,",
            "onResetUserPassword,",
            "onActivateUser,",
            "onDeactivateUser,",
            "onAssignUserRole,",
            "onRemoveUserRole,",
            "onRefreshAdminData,",
            "useLocation();",
            "useNavigate();",
            "new URLSearchParams(search)",
            "normalizeSearchValue",
            "AdminPageActions",
            "AdminFilterPanel",
            "AdminCreatePanel",
            "UserForm",
            "UserDetailPanel",
            "SmallTable",
            "selectedRowId={selectedUser?.id}",
            "onOpenUser(row.id)",
            "buildEnrollmentsPath",
            "buildDocumentsPath",
        ],
    )

    require_contains(
        "frontend/src/pages/OrganizationsPage.jsx",
        [
            "export function OrganizationsPage({",
            "user,",
            "organizations,",
            "loading,",
            "selectedOrganization,",
            "selectedOrganizationLoading,",
            "selectedOrganizationError,",
            "onOpenOrganization,",
            "onCloseOrganization,",
            "onCreateOrganization,",
            "onUpdateOrganization,",
            "onDeleteOrganization,",
            "onRefreshAdminData,",
            "useLocation();",
            "useNavigate();",
            "getOrganizationFiltersFromSearch",
            "AdminPageActions",
            "AdminCreatePanel",
            "AdminFilterPanel",
            "OrganizationForm",
            "OrganizationDetailPanel",
            "SmallTable",
            "selectedRowId={selectedOrganization?.id}",
            "onOpenOrganization(row.id)",
            "buildOrganizationsPath",
            "buildGroupsPath",
            "buildEnrollmentsPath",
        ],
    )

    require_contains(
        "frontend/src/pages/GroupsPage.jsx",
        [
            "getAdminUsers,",
            "getOrgLearningGroupMembers,",
            "addOrgLearningGroupMember,",
            "removeOrgLearningGroupMember,",
            "function LearningGroupForm({",
            "function LearningGroupMembersPanel({ groupDetail })",
            "async function reloadMemberData()",
            "Promise.all([",
            "getOrgLearningGroupMembers(groupDetail.id)",
            "getAdminUsers()",
            "async function handleAddMember(event)",
            "addOrgLearningGroupMember(groupDetail.id",
            "async function handleRemoveMember(userId, userEmail)",
            "removeOrgLearningGroupMember(groupDetail.id, userId)",
            "export function GroupsPage({",
            "user,",
            "groups,",
            "organizations,",
            "loading,",
            "selectedGroup,",
            "selectedGroupLoading,",
            "selectedGroupError,",
            "onOpenGroup,",
            "onCloseGroup,",
            "onCreateGroup,",
            "onUpdateGroup,",
            "onDeleteGroup,",
            "onRefreshAdminData,",
            "useLocation();",
            "useNavigate();",
            "getGroupFiltersFromSearch",
            "calculateGroupCounts",
            "AdminPageActions",
            "AdminCreatePanel",
            "AdminFilterPanel",
            "LearningGroupForm",
            "LearningGroupMembersPanel",
            "SmallTable",
            "selectedRowId={selectedGroup?.id}",
            "onOpenGroup(row.id)",
            "buildGroupsPath",
            "buildEnrollmentsPath",
            "getGroupAttentionItems",
            "groupAttentionItems",
            "group-attention-diagnostics",
            "group-attention-count",
            "group-attention-diagnostics-note",
            "Что требует внимания в группе",
            "Диагностика основана на статусе, коде, организации и описании группы.",
            "Статус: группа неактивна, проверьте актуальность назначений и участников.",
            "Код группы: не заполнен, сложнее искать группу в операционных списках.",
            "Организация: группа не привязана к организации.",
            "Описание: не заполнено, добавьте контекст обучения или состава группы.",
            "group-related-records-links",
            "Связанные записи группы",
            "group-organization-link",
            "group-enrollments-link",
            "group-action-required-enrollments-link",
            "group-action-required-documents-link",
            "learning_group_id: groupDetail.id",
            "action_required: \"true\"",
        ],
    )

    require_contains(
        "frontend/src/pages/RolesPage.jsx",
        [
            "const SYSTEM_ROLE_CODES = new Set([",
            "function isSystemRole(role)",
            "function roleMatchesSearch(role, query)",
            "function roleMatchesType(role, filter)",
            "const ROLE_TYPE_FILTERS = [",
            "function getRoleFiltersFromSearch(search)",
            "function calculateRoleCounts(items)",
            "function RolesSummaryCards({ roles, permissions, roleCounts })",
            "function RolesWorkflowPanel({ roles, permissions, roleCounts })",
            "export function RolesPage({",
            "roles,",
            "permissions,",
            "selectedRole,",
            "onOpenRole,",
            "onCreateRole,",
            "onUpdateRole,",
            "onDeleteRole,",
            "onAssignRolePermission,",
            "onRemoveRolePermission,",
            "useLocation();",
            "useNavigate();",
            "AdminPageActions",
            "AdminCreatePanel",
            "RoleForm",
            "AdminFilterPanel",
            "AdminQuickFilterButtons",
            "SmallTable",
            "selectedRowId={selectedRole?.id}",
            "onOpenRole(row.id)",
            "buildUsersPath({ role_id: row.id })",
            "buildPermissionsPath({ q: row.code })",
            "RoleDetailPanel",
        ],
    )

    require_contains(
        "frontend/src/pages/PermissionsPage.jsx",
        [
            "const ALL_PERMISSION_GROUPS = \"all\";",
            "function getPermissionGroup(permission)",
            "function getPermissionSearchText(permission)",
            "function getPermissionGroupTone(group)",
            "function getPermissionFiltersFromSearch(search)",
            "function calculatePermissionGroupCounts(items)",
            "function PermissionsSummaryCards({ permissions, permissionGroups, permissionGroupCounts })",
            "function PermissionsWorkflowPanel({ permissionGroupCounts })",
            "export function PermissionsPage({",
            "permissions,",
            "selectedPermission,",
            "selectedPermissionLoading,",
            "selectedPermissionError,",
            "onOpenPermission,",
            "onClosePermission,",
            "onRefreshAdminData,",
            "useLocation();",
            "useNavigate();",
            "AdminPageActions",
            "AdminFilterPanel",
            "AdminQuickFilterButtons",
            "SmallTable",
            "selectedRowId={selectedPermission?.id}",
            "onOpenPermission(row.id)",
            "buildRolesPath({ q: row.code })",
            "PermissionDetailPanel",
        ],
    )

    require_contains(
        "frontend/src/pages/AuditPage.jsx",
        [
            "const DEFAULT_FILTERS = {",
            "function normalizeFilters(filters)",
            "function getAuditFiltersFromSearch(search)",
            "function getLimitNumber(filters)",
            "function getAuditFilterPayload(filters)",
            "function getActionTone(action)",
            "function getEntityTone(entityType)",
            "function calculateAuditCounts(events)",
            "function AuditSummaryCards({ auditCounts, filters })",
            "function AuditWorkflowPanel({ auditCounts })",
            "export function AuditPage({",
            "auditEvents,",
            "selectedAuditEvent,",
            "selectedAuditEventLoading,",
            "selectedAuditEventError,",
            "onOpenAuditEvent,",
            "onCloseAuditEvent,",
            "onApplyAuditFilters,",
            "useLocation();",
            "useNavigate();",
            "async function applyAuditFilters(nextFilters)",
            "await onApplyAuditFilters(payload);",
            "async function navigateToAuditFilters(nextFilters",
            "async function handleQuickFilter(field, value)",
            "async function handleSubmit(event)",
            "async function handleReset()",
            "QuickValueFilters",
            "SmallTable",
            "selectedRowId={selectedAuditEvent?.id}",
            "onOpenAuditEvent(row.id)",
            "buildEntityAdminPath(row)",
            "buildAuditPath({",
            "AuditEventDetailPanel",
            "enrollmentEventsCount",
            "organizationEventsCount",
            "audit-document-pdf-workflow",
            "Document/PDF-контур",
            "Регенерация PDF",
            "Создание документов",
            "Отзывы документов",
            "Восстановления документов",
            "buildAuditPath({ action: \"admin.document_regenerated\" })",
            "buildAuditPath({ action: \"admin.document_created\" })",
            "buildAuditPath({ action: \"admin.document_revoked\" })",
            "buildAuditPath({ action: \"admin.document_restored\" })",
            "buildAuditPath({ entity_type: \"enrollment\" })",
            "buildAuditPath({ entity_type: \"organization\" })",
        ],
    )

    require_contains(
        "frontend/src/pages/AdminCoursesPage.jsx",
        [
            "activateAdminCourse,",
            "createAdminCourse,",
            "deactivateAdminCourse,",
            "deleteAdminCourse,",
            "getAdminCourses,",
            "updateAdminCourse",
            "const COURSE_ACTIVE_FILTERS = [",
            "const EMPTY_COURSE_FORM = {",
            "const EMPTY_EDIT_FORM = {",
            "function normalizeHoursInput(value)",
            "function getCourseFiltersFromSearch(search)",
            "function calculateCourseCounts(items)",
            "function buildEditForm(course)",
            "function getCourseStatusTone(course)",
            "function getCourseStatusLabel(course)",
            "function formatCourseApiError(err, fallback)",
            "function CourseFormFields({ values, onChange, prefix = \"\" })",
            "function CourseCard({",
            "export function AdminCoursesPage()",
            "useLocation();",
            "useNavigate();",
            "const [courses, setCourses] = useState([]);",
            "const [courseCounts, setCourseCounts] = useState({",
            "const [showCreateForm, setShowCreateForm] = useState(false);",
            "getAdminCourses",
            "createAdminCourse",
            "updateAdminCourse",
            "async function handleToggleActive",
            "activateAdminCourse",
            "deactivateAdminCourse",
            "deleteAdminCourse",
            "AdminPageActions",
            "AdminCreatePanel",
            "AdminFilterPanel",
            "AdminQuickFilterButtons",
            "AdminEmptyState",
            "CourseCard",
            "buildCoursesPath",
            "buildEnrollmentsPath",
        ],
    )

    require_contains(
        "frontend/src/pages/AdminEnrollmentsPage.jsx",
        [
            "createAdminEnrollment,",
            "createAdminGroupEnrollments,",
            "deleteAdminEnrollment,",
            "getAdminCourses,",
            "getAdminEnrollments,",
            "getAdminOrganizations,",
            "getAdminUsers,",
            "getOrgLearningGroupMembers,",
            "getOrgLearningGroups,",
            "updateAdminEnrollment,",
            "const ENROLLMENT_STATUSES = [",
            "const ENROLLMENT_STATUS_FILTERS = [",
            "const ENROLLMENT_API_ERROR_MESSAGES = {",
            "function getStatusLabel(value)",
            "function formatEnrollmentApiError(err, fallback)",
            "function getEnrollmentFiltersFromSearch(search)",
            "function getStatusTone(value)",
            "function getUserRoleCodes(user)",
            "function isLearnerUser(user)",
            "function isAdminUser(user)",
            "function getUserRoleLabel(user)",
            "function buildUserLabel(user)",
            "function buildCourseLabel(course)",
            "function buildOrganizationsMap(organizations)",
            "function buildGroupsMap(groups)",
            "function groupHasMember(groupId, userId, membersByGroupId)",
            "function buildGroupLabel(group, organizationsById = {})",
            "function getAvailableGroups(",
            "function buildEditForm(enrollment)",
            "function normalizeDateTime(value)",
            "function EnrollmentSummaryCards({ statusCounts, users, courses, groups })",
            "function EnrollmentWorkflowPanel({ statusCounts, courses, groups })",
            "export function AdminEnrollmentsPage()",
            "useLocation();",
            "useNavigate();",
            "const [enrollments, setEnrollments] = useState([]);",
            "showActionRequiredOnly",
            "setFilterActionRequired(\"\")",
            "actionRequiredCount",
            "visibleEnrollments",
            "\u041f\u043e\u043a\u0430\u0437\u0430\u043d\u043e \u043d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0439: {visibleEnrollments.length}",
            r'{"\u0422\u0440\u0435\u0431\u0443\u044e\u0442 \u0434\u0435\u0439\u0441\u0442\u0432\u0438\u044f"}: {actionRequiredCount}',
            "data-testid=\"enrollments-action-required-filter\"",
            r"\u0422\u0440\u0435\u0431\u0443\u044e\u0442 \u0434\u0435\u0439\u0441\u0442\u0432\u0438\u044f",
            "actionRequiredCount",
            "action_required: overrides.action_required ?? filterActionRequired",
            "const [users, setUsers] = useState([]);",
            "const [courses, setCourses] = useState([]);",
            "const [organizations, setOrganizations] = useState([]);",
            "const [groups, setGroups] = useState([]);",
            "const [bulkForm, setBulkForm] = useState({",
            "const [editForm, setEditForm] = useState({",
            "getAdminEnrollments",
            "getAdminUsers",
            "getAdminCourses",
            "getAdminOrganizations",
            "getOrgLearningGroups",
            "getOrgLearningGroupMembers",
            "createAdminEnrollment",
            "createAdminGroupEnrollments",
            "updateAdminEnrollment",
            "deleteAdminEnrollment",
            "AdminQuickFilterButtons",
            "AdminEmptyState",
            "buildCoursesPath",
            "buildDocumentsPath",
            "buildEnrollmentsPath",
            "buildGroupsPath",
        ],
    )

    require_occurs("frontend/src/pages/UsersPage.jsx", "useMemo(", 3)
    require_occurs("frontend/src/pages/OrganizationsPage.jsx", "useMemo(", 2)
    require_occurs("frontend/src/pages/GroupsPage.jsx", "useMemo(", 4)
    require_occurs("frontend/src/pages/RolesPage.jsx", "useMemo(", 3)
    require_occurs("frontend/src/pages/PermissionsPage.jsx", "useMemo(", 3)
    require_occurs("frontend/src/pages/AuditPage.jsx", "useMemo(", 3)
    require_occurs("frontend/src/pages/AdminCoursesPage.jsx", "useState(", 8)
    require_occurs("frontend/src/pages/AdminEnrollmentsPage.jsx", "useState(", 10)

    require_contains(
        "frontend/src/components/admin/OrganizationForm.jsx",
        [
            "organization-form-document-profile-hint",
            "Профиль итогового PDF",
            "Эти поля попадут в PDF-шаблоны удостоверений, сертификатов и справок",
            "Заполните их до публикации документов",
            "fallback-настройки приложения",
        ],
    )

    require_contains(
        "frontend/src/components/admin/OrganizationDetailPanel.jsx",
        [
            "organization-document-profile-card",
            "Профиль итогового PDF",
            "Эти значения используются в PDF-шаблонах удостоверений, сертификатов и справок",
            "Если поле пустое, при генерации документа может использоваться fallback-настройка приложения.",
        ],
    )

    print("Frontend admin pages behavior smoke passed")


if __name__ == "__main__":
    main()
