# lesson studio quiz smoke coverage markers: begin
# These paths are intentionally referenced so check_frontend_smoke_coverage.py
# treats Lesson Studio quiz components as covered by admin component smoke checks.
# smoke-coverage: frontend/src/components/admin/lesson-studio/quiz/QuizAttemptPreview.jsx
# smoke-coverage: frontend/src/components/admin/lesson-studio/quiz/QuizBlockEditor.jsx
# smoke-coverage: frontend/src/components/admin/lesson-studio/quiz/quizGrading.js
# smoke-coverage: frontend/src/components/admin/lesson-studio/quiz/quizSchema.js
# smoke-coverage: frontend/src/components/admin/lesson-studio/quiz/quizValidation.js
# lesson studio quiz smoke coverage markers: end

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def read_text(relative_path: str) -> str:
    path = ROOT / relative_path

    if not path.exists():
        raise SystemExit(f"File not found: {relative_path}")

    return path.read_text(encoding="utf-8")


def require_contains(relative_path: str, fragments: list[str]) -> None:
    text = read_text(relative_path)
    missing = [fragment for fragment in fragments if fragment not in text]

    if missing:
        print(f"{relative_path} is missing required fragments:")
        for fragment in missing:
            print(f" - {fragment}")
        raise SystemExit(1)


def main() -> None:
    require_contains(
        "frontend/src/components/admin/AdminCreatePanel.jsx",
        [
            "export function AdminCreatePanel({",
            "children",
        ],
    )

    require_contains(
        "frontend/src/components/admin/AdminEmptyState.jsx",
        [
            "export function AdminEmptyState({",
        ],
    )

    require_contains(
        "frontend/src/components/admin/AdminFilterField.jsx",
        [
            "export function AdminFilterField({",
        ],
    )

    require_contains(
        "frontend/src/components/admin/AdminFilterPanel.jsx",
        [
            'import { ActionButton } from "../ui/ActionButton";',
            "export function AdminFilterPanel({",
            "children",
            "onReset",
            "resetDisabled",
            "resetLabel",
            "summary",
            "columnsClassName",
            "ActionButton",
            "onClick={onReset}",
            "disabled={resetDisabled}",
            "{summary &&",
        ],
    )

    require_contains(
        "frontend/src/components/admin/AdminFormField.jsx",
        [
            "export function AdminFormField({",
            "label,",
            "required = false",
            "children,",
            "hint,",
            'contentClassName = "mt-1"',
            "{label}{required ?",
            "<div className={contentClassName}>{children}</div>",
            "{hint &&",
        ],
    )

    require_contains(
        "frontend/src/components/admin/AdminPageActions.jsx",
        [
            'import { ActionButton } from "../ui/ActionButton";',
            "export function AdminPageActions({",
            "loading = false",
            "onRefresh,",
            "refreshLabel",
            "refreshingLabel",
            "primaryLabel,",
            "primaryTone =",
            "primaryDisabled = false",
            "onPrimaryClick,",
            "children,",
            "onRefresh &&",
            "loading ? refreshingLabel : refreshLabel",
            "primaryLabel && onPrimaryClick",
            "tone={primaryTone}",
            "disabled={loading || primaryDisabled}",
            "{children}",
        ],
    )

    require_contains(
        "frontend/src/components/admin/AdminQuickFilterButtons.jsx",
        [
            "export function AdminQuickFilterButtons({",
            "items,",
            "activeValue,",
            "counts = {}",
            "disabled = false",
            "onChange,",
            "getCount = (item, currentCounts)",
            "getKey = (item)",
            "items.map((item) => {",
            "const isActive = activeValue === item.value;",
            "const count = getCount(item, counts);",
            "key={getKey(item)}",
            "onClick={() => onChange(item.value)}",
            "{item.label}",
            "{count}",
        ],
    )

    require_contains(
        "frontend/src/components/admin/AdminQuickValueFilters.jsx",
        [
            "export function AdminQuickValueFilters({",
            "title,",
            "value,",
            "items,",
            "counts = {}",
            "disabled = false",
            "onChange,",
            "emptyLabel =",
            "if (items.length === 0)",
            "return null;",
            "onClick={() => onChange(\"\")}",
            "items.map((item) => {",
            "const isActive = value === item;",
            "const count = counts[item] || 0;",
            "onClick={() => onChange(item)}",
            "{count}",
        ],
    )

    require_contains(
        "frontend/src/components/admin/AdminReadOnlyPanel.jsx",
        [
            'import { SectionCard } from "../ui/SectionCard";',
            'import { SmallTable } from "../ui/SmallTable";',
            "export function AdminReadOnlyPanel({",
            "user,",
            "adminData,",
            "activeTab,",
            "onTabChange,",
            "<SectionCard",
            "!user ?",
            "onClick={() => onTabChange(key)}",
            'activeTab === "users"',
            'activeTab === "roles"',
            'activeTab === "permissions"',
            'activeTab === "audit"',
            "<SmallTable",
            "rows={adminData.users}",
            "rows={adminData.roles}",
            "rows={adminData.permissions}",
            "rows={adminData.auditEvents}",
            "JSON.stringify(row.payload)",
        ],
    )

    require_contains(
        "frontend/src/components/admin/AdminTextInput.jsx",
        [
            "ADMIN_FILTER_CONTROL_SOFT_CLASS",
            "ADMIN_FILTER_CONTROL_SUBTLE_DISABLED_CLASS",
            "const ADMIN_FORM_TEXT_INPUT_CLASS",
            "const ADMIN_FORM_TEXT_AREA_CLASS",
            "const ADMIN_FORM_SELECT_INPUT_CLASS",
            "const VARIANT_CLASS_NAMES = {",
            "export function AdminTextInput({ className = \"\", variant = \"soft\", ...props })",
            "const baseClassName = VARIANT_CLASS_NAMES[variant] || VARIANT_CLASS_NAMES.soft;",
            "return <input {...props} className={mergedClassName} />;",
            "export function AdminSubtleTextInput(props)",
            "export function AdminFormTextInput(props)",
            "export function AdminFormTextArea({ className = \"\", ...props })",
            "return <textarea {...props} className={mergedClassName} />;",
            "export function AdminFormSelectInput({ className = \"\", ...props })",
            "return <select {...props} className={mergedClassName} />;",
        ],
    )

    require_contains(
        "frontend/src/components/admin/AdminWorkCenter.jsx",
        [
            'import { Link } from "react-router-dom";',
            "export function getAdminToneClasses(tone)",
            'if (tone === "green")',
            'if (tone === "amber")',
            'if (tone === "red")',
            'if (tone === "violet")',
            'if (tone === "gray")',
            "export function AdminMetricCard({",
            "title,",
            "label,",
            "value,",
            "hint,",
            "to,",
            "tone =",
            "const cardTitle = title || label;",
            "getAdminToneClasses(tone)",
            "if (!to)",
            "<Link to={to}",
            "export function AdminSignalCard({",
            "export function AdminSummaryCard({ title, value, hint, to })",
            "export function AdminWorkflowLink({ title, description, to })",
        ],
    )

    require_contains(
        "frontend/src/components/admin/AuditEventDetailPanel.jsx",
        [
            'import { Link } from "react-router-dom";',
            'import { Alert } from "../ui/Alert";',
            'import { DetailField, formatDetailDate } from "../ui/DetailField";',
            'import { JsonBlock } from "../ui/JsonBlock";',
            'import { LoadingBlock } from "../ui/LoadingBlock";',
            'import { SectionCard } from "../ui/SectionCard";',
            'import { StatusBadge } from "../ui/StatusBadge";',
            "PANEL_LINK_CLASS, buildAuditPath, buildEntityAdminPath",
            "export function AuditEventDetailPanel({",
            "auditEventDetail,",
            "loading,",
            "error,",
            "onClose,",
            "const entityAdminPath = buildEntityAdminPath(auditEventDetail);",
            "!auditEventDetail && !loading && !error",
            "loading && <LoadingBlock",
            "error &&",
            "auditEventDetail && !loading",
            "onClick={onClose}",
            "buildAuditPath({",
            "entityAdminPath &&",
            "<DetailField label=\"ID\" value={auditEventDetail.id} />",
            "formatDetailDate(auditEventDetail.created_at)",
            "<JsonBlock value={auditEventDetail.payload} />",
            "AUDIT_RELATED_LINK_CLASS",
            "AUDIT_ATTENTION_LINK_CLASS",
            "getAuditAttentionItems",
            "auditAttentionItems",
            "audit-attention-diagnostics",
            "audit-attention-count",
            "audit-attention-diagnostics-note",
            "Что требует внимания в событии аудита",
            "Диагностика основана на action, entity, actor, IP и user agent события.",
            "Action: не заполнен, событие сложнее классифицировать в расследовании.",
            "Entity type: не заполнен, событие нельзя быстро связать с разделом.",
            "Entity ID: не заполнен, история конкретной сущности недоступна.",
            "Actor: не указан, событие выглядит системным или требует проверки источника.",
            "audit-investigation-links",
            "Связи расследования",
            "audit-action-link",
            "audit-entity-type-link",
            "audit-entity-history-link",
            "audit-actor-link",
            "audit-expanded-limit-link",
            "audit-entity-admin-link",
            "Все события action",
            "Все события actor",
            "Последние 200 событий",
            "buildAuditPath({ action: auditEventDetail.action })",
            "buildAuditPath({ entity_type: auditEventDetail.entity_type })",
            "buildAuditPath({ actor_user_id: auditEventDetail.actor_user_id })",
            "buildAuditPath({ limit: \"200\" })",
        ],
    )

    require_contains(
        "frontend/src/components/admin/OrganizationDetailPanel.jsx",
        [
            'import { useState } from "react";',
            "OrganizationForm,",
            "ORGANIZATION_API_ERROR_MESSAGES,",
            "formatOrganizationApiError,",
            'import { ActionButton } from "../ui/ActionButton";',
            'import { Alert } from "../ui/Alert";',
            'import { DetailField, formatDetailDate } from "../ui/DetailField";',
            'import { LoadingBlock } from "../ui/LoadingBlock";',
            'import { SectionCard } from "../ui/SectionCard";',
            'import { StatusBadge } from "../ui/StatusBadge";',
            'import { buildAuditPath, buildDocumentsPath, buildEnrollmentsPath, buildGroupsPath } from "../../utils/adminLinks";',
            'import { Link } from "react-router-dom";',
            "export function OrganizationDetailPanel({",
            "organizationDetail,",
            "onUpdateOrganization,",
            "onDeleteOrganization,",
            "const [isEditing, setIsEditing] = useState(false);",
            "const [deleting, setDeleting] = useState(false);",
            "function handleClose()",
            "async function handleDelete()",
            "window.confirm(",
            "await onDeleteOrganization(organizationDetail.id);",
            "formatOrganizationApiError(err, ORGANIZATION_API_ERROR_MESSAGES.deleteFailed)",
            "!organizationDetail && !loading && !error",
            "loading && <LoadingBlock",
            "error &&",
            "organizationDetail && !loading",
            "onClick={() => setIsEditing(true)}",
            "onClick={handleDelete}",
            "onClick={handleClose}",
            "isEditing ?",
            "<OrganizationForm",
            "onSubmit={(payload) => onUpdateOrganization(organizationDetail.id, payload)}",
            "<StatusBadge tone=\"blue\">organization</StatusBadge>",
            "formatDetailDate(organizationDetail.created_at)",
            "formatDetailDate(organizationDetail.updated_at)",
            "organization-related-records-links",
            "Связанные записи",
            "Назначения организации",
            "Документы организации",
            "Аудит организации",
            "organization-audit-link",
            "buildAuditPath({ entity_type: \"organization\", entity_id: organizationDetail.id })",
            "buildEnrollmentsPath({ organization_id: organizationDetail.id })",
            "buildDocumentsPath({ organization_id: organizationDetail.id })",
            "buildGroupsPath",
            "getOrganizationAttentionItems",
            "ORGANIZATION_DOCUMENT_PROFILE_FIELDS",
            "organizationAttentionItems",
            "organization-attention-diagnostics",
            "organization-attention-count",
            "organization-attention-diagnostics-note",
            "Что требует внимания в организации",
            "Диагностика основана на реквизитах, адресах и PDF-профиле организации.",
            "КПП: не заполнен, проверьте реквизиты юридического лица.",
            "ОГРН: не заполнен, проверьте регистрационные данные организации.",
            "Юридический адрес: не заполнен.",
            "Фактический адрес: не заполнен.",
            "PDF-профиль: не заполнено полей",
            "organization-groups-link",
            "organization-action-required-enrollments-link",
            "organization-action-required-documents-link",
            "Группы организации",
            "Проблемные назначения",
            "Проблемные документы",
            "buildGroupsPath({ organization_id: organizationDetail.id })",
            "action_required: \"true\"",
        ],
    )

    require_contains(
        "frontend/src/components/admin/OrganizationForm.jsx",
        [
            'import { getApiErrorMessage, getApiErrorStatus, getSafeApiErrorMessage } from "../../utils/apiErrors";',
            'import { useState } from "react";',
            'import { ActionButton } from "../ui/ActionButton";',
            'import { Alert } from "../ui/Alert";',
            "AdminFormTextArea as TextArea",
            "AdminFormTextInput as TextInput",
            'import { AdminFormField as Field } from "./AdminFormField";',
            "const EMPTY_ORGANIZATION = {",
            "export const ORGANIZATION_API_ERROR_MESSAGES = {",
            "saveFailed:",
            "createFailed:",
            "updateFailed:",
            "deleteFailed:",
            "accessDenied:",
            "notFound:",
            "duplicateInn:",
            "deleteHasAssignments:",
            "invalidRequest:",
            "export function formatOrganizationApiError(err, fallback)",
            "const status = getApiErrorStatus(err);",
            "const message = getApiErrorMessage(err);",
            "const safeMessage = getSafeApiErrorMessage(message, fallback);",
            "readableMessage = safeMessage;",
            "normalizedMessage.includes(\"inn\")",
            "normalizedMessage.includes(\"no fields\")",
            "function normalizeInitialValues(initialValues)",
            "function nullableTrim(value)",
            "function buildPayload(values)",
            "export function OrganizationForm({",
            "initialValues = EMPTY_ORGANIZATION",
            "async function handleSubmit(event)",
            "const payload = buildPayload(values);",
            "const result = await onSubmit(payload);",
            "setError(formatOrganizationApiError(err, errorMessage));",
            "const isInvalid = !values.inn.trim() || !values.name.trim();",
            "<Field label=",
            "value={values.inn}",
            "value={values.name}",
            "value={values.kpp}",
            "value={values.ogrn}",
            "value={values.legal_address}",
            "value={values.actual_address}",
            "disabled={loading || isInvalid}",
        ],
    )

    require_contains(
        "frontend/src/components/admin/PermissionDetailPanel.jsx",
        [
            'import { Alert } from "../ui/Alert";',
            'import { DetailField, formatDetailDate } from "../ui/DetailField";',
            'import { LoadingBlock } from "../ui/LoadingBlock";',
            'import { SectionCard } from "../ui/SectionCard";',
            'import { StatusBadge } from "../ui/StatusBadge";',
            "export function PermissionDetailPanel({",
            "permissionDetail,",
            "loading,",
            "error,",
            "onClose,",
            "!permissionDetail && !loading && !error",
            "loading && <LoadingBlock",
            "error &&",
            "permissionDetail && !loading",
            "onClick={onClose}",
            "<StatusBadge tone=\"blue\">",
            "roles: {permissionDetail.roles?.length || 0}",
            "formatDetailDate(permissionDetail.created_at)",
            "formatDetailDate(permissionDetail.updated_at)",
            "permissionDetail.roles?.length",
            "permissionDetail.roles.map((role)",
        ],
    )

    require_contains(
        "frontend/src/components/admin/RbacResult.jsx",
        [
            'import { SectionCard } from "../ui/SectionCard";',
            "export function RbacResult({ rbac })",
            "<SectionCard title=\"RBAC result\">",
            "!rbac ?",
            "JSON.stringify(rbac, null, 2)",
        ],
    )

    require_contains(
        "frontend/src/components/admin/RoleDetailPanel.jsx",
        [
            'import { useMemo, useState } from "react";',
            'import { ActionButton } from "../ui/ActionButton";',
            'import { Alert } from "../ui/Alert";',
            'import { DetailField, formatDetailDate } from "../ui/DetailField";',
            'import { LoadingBlock } from "../ui/LoadingBlock";',
            'import { SectionCard } from "../ui/SectionCard";',
            'import { StatusBadge } from "../ui/StatusBadge";',
            "RoleForm,",
            "ROLE_API_ERROR_MESSAGES,",
            "formatRoleApiError,",
            'import { AdminFormField as Field } from "./AdminFormField";',
            'import { AdminFormSelectInput as SelectInput } from "./AdminTextInput";',
            "const SYSTEM_ROLE_CODES = new Set([",
            "function RolePermissionAssignmentForm({ permissions, assignedPermissions, onAssign })",
            "const assignedIds = useMemo(",
            "const availablePermissions = useMemo(",
            "const selectedPermissionId = availablePermissions.some",
            "await onAssign({ permission_id: selectedPermissionId });",
            "formatRoleApiError(err, ROLE_API_ERROR_MESSAGES.addPermissionFailed)",
            "if (!permissions?.length)",
            "if (!availablePermissions.length)",
            "export function RoleDetailPanel({",
            "roleDetail,",
            "permissions,",
            "onAssignPermission,",
            "onRemovePermission,",
            "onUpdateRole,",
            "onDeleteRole,",
            "const [editingMetadata, setEditingMetadata] = useState(false);",
            "const isSystemAdminRole = roleDetail?.code === \"admin\";",
            "const isSystemRole = SYSTEM_ROLE_CODES.has(roleDetail?.code);",
            "async function handleUpdateRole(payload)",
            "async function handleAssignPermission(payload)",
            "async function handleDeleteRole()",
            "async function handleRemovePermission(rolePermissionId)",
            "!roleDetail && !loading && !error",
            "loading && <LoadingBlock",
            "error &&",
            "roleDetail && !loading",
            "isSystemAdminRole &&",
            "isSystemRole && !isSystemAdminRole",
            "!isSystemRole &&",
            "editingMetadata && !isSystemRole",
            "<RoleForm",
            "roleDetail.permissions.map((permission)",
            "handleRemovePermission(permission.role_permission_id)",
            "<RolePermissionAssignmentForm",
            'import { Link } from "react-router-dom";',
            "buildAuditPath, buildPermissionsPath, buildUsersPath",
            "ROLE_RELATED_LINK_CLASS",
            "ROLE_ATTENTION_LINK_CLASS",
            "getRoleAttentionItems",
            "roleAttentionItems",
            "role-attention-diagnostics",
            "role-attention-count",
            "role-attention-diagnostics-note",
            "Что требует внимания в роли",
            "Диагностика основана на типе роли, защите системных ролей, описании и составе permissions.",
            "Admin: системная роль защищена от изменения permissions, чтобы не потерять административный доступ.",
            "Тип роли: системная роль защищена seed-логикой, редактируйте только пользовательские роли.",
            "Тип роли: пользовательская роль, перед удалением проверьте назначения пользователям.",
            "Описание: не заполнено, сложнее понять назначение роли и границы доступа.",
            "Permissions: права не назначены, роль не даёт прикладного доступа.",
            "role-related-records-links",
            "Связанные записи роли",
            "role-users-link",
            "role-permissions-link",
            "role-admin-permissions-link",
            "role-audit-link",
            "role-permission-audit-link",
            "Пользователи с этой ролью",
            "Аудит permissions",
            "buildUsersPath({ role: roleDetail.code })",
            "buildPermissionsPath({ group: \"admin\" })",
            "buildAuditPath({ entity_type: \"role\", entity_id: roleDetail.id })",
            "buildAuditPath({ entity_type: \"permission\" })",
        ],
    )

    require_contains(
        "frontend/src/components/admin/RoleForm.jsx",
        [
            'import { getApiErrorMessage, getApiErrorStatus, getSafeApiErrorMessage } from "../../utils/apiErrors";',
            'import { useState } from "react";',
            'import { ActionButton } from "../ui/ActionButton";',
            'import { Alert } from "../ui/Alert";',
            "AdminFormTextArea as TextArea",
            "AdminFormTextInput as TextInput",
            'import { AdminFormField as Field } from "./AdminFormField";',
            "const EMPTY_ROLE = {",
            "export const ROLE_API_ERROR_MESSAGES = {",
            "saveFailed:",
            "createFailed:",
            "updateFailed:",
            "deleteFailed:",
            "addPermissionFailed:",
            "removePermissionFailed:",
            "accessDenied:",
            "roleNotFound:",
            "permissionNotFound:",
            "duplicateRoleCode:",
            "duplicatePermission:",
            "systemRoleProtected:",
            "systemPermissionsProtected:",
            "deleteHasAssignments:",
            "invalidRequest:",
            "export function formatRoleApiError(err, fallback)",
            "const status = getApiErrorStatus(err);",
            "const message = getApiErrorMessage(err);",
            "const safeMessage = getSafeApiErrorMessage(message, fallback);",
            "readableMessage = safeMessage;",
            "normalizedMessage.includes(\"permission\")",
            "normalizedMessage.includes(\"system role\")",
            "normalizedMessage.includes(\"no fields\")",
            "function normalizeInitialValues(initialValues)",
            "function nullableTrim(value)",
            "function buildPayload(values, mode)",
            "if (mode === \"create\")",
            "payload.code = values.code.trim().toLowerCase();",
            "export function RoleForm({",
            "mode = \"create\"",
            "async function handleSubmit(event)",
            "const payload = buildPayload(values, mode);",
            "const result = await onSubmit(payload);",
            "setError(formatRoleApiError(err, errorMessage));",
            "const isInvalid =",
            "mode === \"create\"",
            "disabled={loading || mode !== \"create\"}",
            "disabled={loading || isInvalid}",
        ],
    )

    require_contains(
        "frontend/src/components/admin/UserDetailPanel.jsx",
        [
            'import { useMemo, useState } from "react";',
            "UserForm,",
            "USER_API_ERROR_MESSAGES,",
            "formatUserApiError,",
            'import { ActionButton } from "../ui/ActionButton";',
            'import { Alert } from "../ui/Alert";',
            'import { DetailField, formatDetailDate } from "../ui/DetailField";',
            'import { LoadingBlock } from "../ui/LoadingBlock";',
            'import { SectionCard } from "../ui/SectionCard";',
            'import { StatusBadge } from "../ui/StatusBadge";',
            'import { AdminFormTextInput as TextInput } from "./AdminTextInput";',
            'import { AdminFormField as Field } from "./AdminFormField";',
            'import { AdminFormSelectInput as SelectInput } from "./AdminTextInput";',
            "function roleBadgeTone(roleCode)",
            "function buildRoleAssignmentInitialValues(roles, organizations)",
            "function UserPasswordResetForm({ onReset })",
            "const canSubmit = password.length >= 8 && password === confirmation;",
            "async function handleSubmit(event)",
            "await onReset(password);",
            "formatUserApiError(err, USER_API_ERROR_MESSAGES.passwordResetFailed)",
            "function UserRoleAssignmentForm({",
            "roles,",
            "organizations,",
            "onAssign,",
            "buildRoleAssignmentInitialValues(roles, organizations)",
            "const canSubmit = Boolean(values.role_id)",
            "await onAssign({",
            "organization_id: values.scope === \"organization\" ? values.organization_id : null",
            "formatUserApiError(err, USER_API_ERROR_MESSAGES.assignRoleFailed)",
            "if (!roles?.length)",
            "export function UserDetailPanel({",
            "userDetail,",
            "roles,",
            "organizations,",
            "onUpdateUser,",
            "onResetUserPassword,",
            "onActivateUser,",
            "onDeactivateUser,",
            "onAssignUserRole,",
            "onRemoveUserRole,",
            "const organizationsById = useMemo(() => {",
            "function handleClose()",
            "async function handleResetPassword(password)",
            "return onResetUserPassword(userDetail.id, password);",
            "async function handleActivate()",
            "await onActivateUser(userDetail.id);",
            "async function handleDeactivate()",
            "await onDeactivateUser(userDetail.id);",
            "async function handleAssignRole(payload)",
            "return onAssignUserRole(userDetail.id, payload);",
            "async function handleRemoveRole(userRoleId)",
            "await onRemoveUserRole(userDetail.id, userRoleId);",
            "!userDetail && !loading && !error",
            "loading && <LoadingBlock",
            "error &&",
            "userDetail && !loading",
            "onClick={() => setIsEditing(true)}",
            "userDetail.is_active ?",
            "onClick={handleDeactivate}",
            "onClick={handleActivate}",
            "onClick={handleClose}",
            "isEditing ?",
            "<UserForm",
            "onSubmit={(payload) => onUpdateUser(userDetail.id, payload)}",
            "userDetail.roles.map((role) => {",
            "organizationsById.get(role.organization_id)",
            "handleRemoveRole(role.id)",
            'import { Link } from "react-router-dom";',
            "buildAuditPath, buildDocumentsPath, buildEnrollmentsPath, buildRolesPath",
            "USER_RELATED_LINK_CLASS",
            "USER_ATTENTION_LINK_CLASS",
            "getUserAttentionItems",
            "userAttentionItems",
            "user-attention-diagnostics",
            "user-attention-count",
            "user-attention-diagnostics-note",
            "Что требует внимания в пользователе",
            "Диагностика основана на активности, подтверждении email, MFA, телефоне и ролях пользователя.",
            "Статус: пользователь неактивен, проверьте необходимость доступа и связанные назначения.",
            "Email: не подтверждён, пользователь может не получать уведомления и восстановление доступа.",
            "MFA: не включена, проверьте требования безопасности для административных ролей.",
            "Телефон: не заполнен, сложнее связаться с пользователем вне системы.",
            "Роли: не назначены, пользователь не сможет работать в административных разделах.",
            "user-related-records-links",
            "Связанные записи пользователя",
            "user-enrollments-link",
            "user-documents-link",
            "user-action-required-enrollments-link",
            "user-roles-link",
            "user-audit-link",
            "buildEnrollmentsPath({ user_id: userDetail.id })",
            "buildDocumentsPath({ user_id: userDetail.id })",
            "buildAuditPath({ entity_type: \"user\", entity_id: userDetail.id })",
            "action_required: \"true\"",
        ],
    )

    require_contains(
        "frontend/src/components/admin/UserForm.jsx",
        [
            'import { getApiErrorMessage, getApiErrorStatus, getSafeApiErrorMessage } from "../../utils/apiErrors";',
            'import { useState } from "react";',
            'import { ActionButton } from "../ui/ActionButton";',
            'import { Alert } from "../ui/Alert";',
            'import { AdminFormTextInput as TextInput } from "./AdminTextInput";',
            'import { AdminFormField as Field } from "./AdminFormField";',
            "export const USER_API_ERROR_MESSAGES = {",
            "saveFailed:",
            "createFailed:",
            "updateFailed:",
            "passwordResetFailed:",
            "activateFailed:",
            "deactivateFailed:",
            "assignRoleFailed:",
            "removeRoleFailed:",
            "accessDenied:",
            "userNotFound:",
            "roleNotFound:",
            "organizationNotFound:",
            "roleAssignmentNotFound:",
            "duplicateEmailOrPhone:",
            "duplicatePhone:",
            "duplicateRoleAssignment:",
            "lastAdminDeactivate:",
            "lastAdminRoleRemove:",
            "invalidPassword:",
            "invalidRequest:",
            "export function formatUserApiError(err, fallback)",
            "const status = getApiErrorStatus(err);",
            "const message = getApiErrorMessage(err);",
            "const safeMessage = getSafeApiErrorMessage(message, fallback);",
            "readableMessage = safeMessage;",
            "normalizedMessage.includes(\"role assignment\")",
            "normalizedMessage.includes(\"organization\")",
            "normalizedMessage.includes(\"last active admin\")",
            "normalizedMessage.includes(\"last admin role\")",
            "normalizedMessage.includes(\"password\")",
            "function normalizeInitialValues(initialValues, mode)",
            "function nullableTrim(value)",
            "function requiredTrim(value)",
            "function buildPayload(values, mode)",
            "if (mode !== \"create\")",
            "export function UserForm({",
            "mode = \"edit\"",
            "const isCreateMode = mode === \"create\";",
            "async function handleSubmit(event)",
            "const payload = buildPayload(values, mode);",
            "const result = await onSubmit(payload);",
            "if (isCreateMode)",
            "setValues(normalizeInitialValues(null, mode));",
            "setError(formatUserApiError(err, errorMessage));",
            "isCreateMode &&",
            "value={values.email}",
            "value={values.password}",
            "value={values.full_name}",
            "value={values.phone}",
            "checked={values.is_active}",
            "checked={values.is_email_verified}",
            "disabled={loading}",
        ],
    )

    require_contains(
        "frontend/src/components/admin/OrganizationForm.jsx",
        [
            "document_issuer_name",
            "document_signer_position",
            "document_signer_name",
            "document_basis",
            "document_place",
            "organization-document-profile-fields",
            "Реквизиты для генерируемых документов",
            "Организация-выдавшая документ",
            "Место выдачи",
            "Должность подписанта",
            "ФИО подписанта",
            "Основание выдачи",
        ],
    )

    require_contains(
        "frontend/src/components/admin/OrganizationDetailPanel.jsx",
        [
            "organization-document-profile-card",
            "document_issuer_name",
            "document_signer_position",
            "document_signer_name",
            "document_basis",
            "document_place",
            "Реквизиты для генерируемых документов",
            "Организация-выдавшая документ",
            "Место выдачи",
            "Должность подписанта",
            "ФИО подписанта",
            "Основание выдачи",
        ],
    )

    print("Admin components behavior smoke passed")


if __name__ == "__main__":
    main()
