from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def read_text(relative_path: str) -> str:
    path = ROOT / relative_path

    if not path.exists():
        raise SystemExit(f"File not found: {relative_path}")

    return path.read_text(encoding="utf-8")


def require_contains(relative_path: str, fragments: list[str]) -> None:
    text = read_text(relative_path)
    missing = [fragment for fragment in fragments if fragment not in text]

    if missing:
        print(f"{relative_path} is missing required fragments:")
        for fragment in missing:
            print(f" - {fragment}")
        raise SystemExit(1)


def main() -> None:
    require_contains(
        "frontend/src/hooks/useAdminDataLoader.js",
        [
            'import { formatApiError } from "../utils/apiErrors";',
            "getAdminAuditEvents,",
            "getAdminOrganizations,",
            "getAdminPermissions,",
            "getAdminRoles,",
            "getAdminUsers,",
            "getOrgLearningGroups,",
            "EMPTY_ADMIN_DATA,",
            "getNowLabel,",
            "sortGroups,",
            "export function useAdminDataLoader({",
            "setAdminData,",
            "setAdminDataLoadedAt,",
            "setAdminLoading,",
            "setError,",
            "async function loadAdminData()",
            "setAdminLoading(true);",
            "setError(\"\");",
            "await Promise.all([",
            "getAdminUsers()",
            "getAdminOrganizations()",
            "getOrgLearningGroups()",
            "getAdminRoles()",
            "getAdminPermissions()",
            "getAdminAuditEvents()",
            "setAdminData({",
            "groups: sortGroups(groups)",
            "setAdminDataLoadedAt(getNowLabel());",
            "setError(formatApiError(err,",
            "setAdminData(EMPTY_ADMIN_DATA);",
            "setAdminDataLoadedAt(\"\");",
            "setAdminLoading(false);",
            "return {",
            "loadAdminData,",
        ],
    )

    require_contains(
        "frontend/src/hooks/useAdminSelections.js",
        [
            'import { formatApiError } from "../utils/apiErrors";',
            'import { useState } from "react";',
            "export function useAdminSelections()",
            "const [selectedUser, setSelectedUser] = useState(null);",
            "const [selectedOrganization, setSelectedOrganization] = useState(null);",
            "const [selectedGroup, setSelectedGroup] = useState(null);",
            "const [selectedRole, setSelectedRole] = useState(null);",
            "const [selectedPermission, setSelectedPermission] = useState(null);",
            "const [selectedAuditEvent, setSelectedAuditEvent] = useState(null);",
            "function clearSelectedUser()",
            "function clearSelectedOrganization()",
            "function clearSelectedGroup()",
            "function clearSelectedRole()",
            "function clearSelectedPermission()",
            "function clearSelectedAuditEvent()",
            "function clearAllSelections()",
            "clearSelectedUser();",
            "clearSelectedOrganization();",
            "clearSelectedGroup();",
            "clearSelectedRole();",
            "clearSelectedPermission();",
            "clearSelectedAuditEvent();",
            "async function openSelection({ setValue, setLoading, setError, load })",
            "const detail = await load();",
            "setValue(detail);",
            "setError(formatApiError(err,",
            "return {",
            "openSelection,",
            "clearAllSelections,",
            "selectedUser,",
            "setSelectedUser,",
            "clearSelectedUser,",
            "selectedOrganization,",
            "setSelectedOrganization,",
            "clearSelectedOrganization,",
            "selectedGroup,",
            "setSelectedGroup,",
            "clearSelectedGroup,",
            "selectedRole,",
            "setSelectedRole,",
            "clearSelectedRole,",
            "selectedPermission,",
            "setSelectedPermission,",
            "clearSelectedPermission,",
            "selectedAuditEvent,",
            "setSelectedAuditEvent,",
            "clearSelectedAuditEvent,",
        ],
    )

    require_contains(
        "frontend/src/hooks/useAdminDetailActions.js",
        [
            "getAdminAuditEventDetail,",
            "getAdminOrganizationDetail,",
            "getAdminPermissionDetail,",
            "getAdminRoleDetail,",
            "getAdminUserDetail,",
            "getOrgLearningGroupDetail,",
            "export function useAdminDetailActions({",
            "openSelection,",
            "async function handleOpenUser(userId)",
            "load: () => getAdminUserDetail(userId)",
            "async function handleOpenOrganization(organizationId)",
            "load: () => getAdminOrganizationDetail(organizationId)",
            "async function handleOpenGroup(groupId)",
            "load: () => getOrgLearningGroupDetail(groupId)",
            "async function handleOpenRole(roleId)",
            "load: () => getAdminRoleDetail(roleId)",
            "async function handleOpenPermission(permissionId)",
            "load: () => getAdminPermissionDetail(permissionId)",
            "async function handleOpenAuditEvent(auditEventId)",
            "load: () => getAdminAuditEventDetail(auditEventId)",
            "return {",
            "handleOpenUser,",
            "handleOpenOrganization,",
            "handleOpenGroup,",
            "handleOpenRole,",
            "handleOpenPermission,",
            "handleOpenAuditEvent,",
        ],
    )

    require_contains(
        "frontend/src/hooks/useAdminEntityActions.js",
        [
            "activateAdminUser,",
            "assignAdminRolePermission,",
            "assignAdminUserRole,",
            "createAdminOrganization,",
            "createAdminRole,",
            "createAdminUser,",
            "createOrgLearningGroup,",
            "deactivateAdminUser,",
            "deleteAdminOrganization,",
            "deleteAdminRole,",
            "deleteOrgLearningGroup,",
            "removeAdminRolePermission,",
            "removeAdminUserRole,",
            "resetAdminUserPassword,",
            "updateAdminOrganization,",
            "updateAdminRole,",
            "updateAdminUser,",
            "updateOrgLearningGroup,",
            "removeAdminCollectionItem,",
            "replaceAdminCollectionItem,",
            "upsertAdminCollectionItem,",
            "sortGroups,",
            "sortOrganizations,",
            "sortRoles,",
            "sortUsers,",
            "export function useAdminEntityActions({",
            "async function handleCreateUser(payload)",
            "const created = await createAdminUser(payload);",
            "upsertAdminCollectionItem(setAdminData, \"users\", created, sortUsers);",
            "async function handleUpdateUser(userId, payload)",
            "const updated = await updateAdminUser(userId, payload);",
            "async function handleResetUserPassword(userId, password)",
            "const updated = await resetAdminUserPassword(userId, password);",
            "async function handleActivateUser(userId)",
            "const updated = await activateAdminUser(userId);",
            "async function handleDeactivateUser(userId)",
            "const updated = await deactivateAdminUser(userId);",
            "async function handleAssignUserRole(userId, payload)",
            "const updated = await assignAdminUserRole(userId, payload);",
            "async function handleRemoveUserRole(userId, userRoleId)",
            "const updated = await removeAdminUserRole(userId, userRoleId);",
            "async function handleCreateOrganization(payload)",
            "const created = await createAdminOrganization(payload);",
            "async function handleUpdateOrganization(organizationId, payload)",
            "const updated = await updateAdminOrganization(organizationId, payload);",
            "async function handleDeleteOrganization(organizationId)",
            "const deleted = await deleteAdminOrganization(organizationId);",
            "async function handleCreateGroup(payload)",
            "const created = await createOrgLearningGroup(payload);",
            "async function handleUpdateGroup(groupId, payload)",
            "const updated = await updateOrgLearningGroup(groupId, payload);",
            "async function handleDeleteGroup(groupId)",
            "const deleted = await deleteOrgLearningGroup(groupId);",
            "async function handleCreateRole(payload)",
            "const created = await createAdminRole(payload);",
            "async function handleUpdateRole(roleId, payload)",
            "const updated = await updateAdminRole(roleId, payload);",
            "async function handleDeleteRole(roleId)",
            "const deleted = await deleteAdminRole(roleId);",
            "async function handleAssignRolePermission(roleId, payload)",
            "const updated = await assignAdminRolePermission(roleId, payload);",
            "async function handleRemoveRolePermission(roleId, rolePermissionId)",
            "const updated = await removeAdminRolePermission(roleId, rolePermissionId);",
            "return {",
            "handleCreateUser,",
            "handleUpdateUser,",
            "handleResetUserPassword,",
            "handleActivateUser,",
            "handleDeactivateUser,",
            "handleAssignUserRole,",
            "handleRemoveUserRole,",
            "handleCreateOrganization,",
            "handleUpdateOrganization,",
            "handleDeleteOrganization,",
            "handleCreateGroup,",
            "handleUpdateGroup,",
            "handleDeleteGroup,",
            "handleCreateRole,",
            "handleUpdateRole,",
            "handleDeleteRole,",
            "handleAssignRolePermission,",
            "handleRemoveRolePermission,",
        ],
    )

    require_contains(
        "frontend/src/hooks/useAdminAuditActions.js",
        [
            'import { formatApiError } from "../utils/apiErrors";',
            'import { getAdminAuditEvents } from "../api/client";',
            "export function useAdminAuditActions({",
            "setAdminData,",
            "setAdminDataLoadedAt,",
            "setAdminLoading,",
            "setError,",
            "clearSelectedAuditEvent,",
            "getNowLabel,",
            "async function handleApplyAuditFilters(filters)",
            "setAdminLoading(true);",
            "setError(\"\");",
            "clearSelectedAuditEvent();",
            "const auditEvents = await getAdminAuditEvents(filters);",
            "setAdminData((current) => ({",
            "auditEvents,",
            "setAdminDataLoadedAt(getNowLabel());",
            "setError(formatApiError(err,",
            "throw err;",
            "setAdminLoading(false);",
            "return {",
            "handleApplyAuditFilters,",
        ],
    )

    require_contains(
        "frontend/src/hooks/useAppNavigation.js",
        [
            'import { useNavigate } from "react-router-dom";',
            'import { getAdminPathForPage } from "../utils/adminRoutes";',
            'import { PUBLIC_ROUTE_MAP } from "../utils/publicRoutes";',
            "export function useAppNavigation({ setCurrentPage })",
            "const navigate = useNavigate();",
            "function handleNavigatePublicPage(pageKey)",
            'if (pageKey === "dashboard" || pageKey === "admin")',
            'navigate("/admin");',
            "navigate(PUBLIC_ROUTE_MAP[pageKey] || \"/\");",
            "function handleNavigateAdminPage(pageKey)",
            "const path = getAdminPathForPage(pageKey);",
            "setCurrentPage(pageKey);",
            "navigate(path);",
            "function handleOpenPublicCourse(courseSlug)",
            "navigate(`/courses/${courseSlug}`);",
            "return {",
            "handleNavigatePublicPage,",
            "handleNavigateAdminPage,",
            "handleOpenPublicCourse,",
        ],
    )

    require_contains(
        "frontend/src/hooks/useAppRouteState.js",
        [
            "getAdminPageFromPathname,",
            "isAdminPathname,",
            'import { getPublicPageFromPathname } from "../utils/publicRoutes";',
            'import { userHasRole } from "../utils/adminState";',
            "export function useAppRouteState({",
            "pathname,",
            "currentPage,",
            "user,",
            "initializingAuth,",
            "const isAdminRoute = isAdminPathname(pathname);",
            "const adminRoutePage = getAdminPageFromPathname(pathname);",
            "const isUnknownAdminRoute = isAdminRoute && !adminRoutePage;",
            "const activeAdminPage = adminRoutePage || currentPage;",
            "const currentPublicPage = getPublicPageFromPathname(pathname);",
            "const isAdmin = userHasRole(user, \"admin\");",
            "const authBadgeText = initializingAuth",
            "const authBadgeTone = initializingAuth",
            "return {",
            "isAdminRoute,",
            "adminRoutePage,",
            "isUnknownAdminRoute,",
            "activeAdminPage,",
            "currentPublicPage,",
            "isAdmin,",
            "authBadgeText,",
            "authBadgeTone,",
        ],
    )

    require_contains(
        "frontend/src/hooks/usePageMeta.js",
        [
            'import { useEffect } from "react";',
            'import { useLocation } from "react-router-dom";',
            'import { isAdminPathname } from "../utils/adminRoutes";',
            "buildPublicMeta,",
            "ensureMetaDescriptionTag,",
            "const ADMIN_META = {",
            "export function usePageMeta()",
            "const location = useLocation();",
            "useEffect(() => {",
            "const meta = isAdminPathname(location.pathname)",
            "? ADMIN_META",
            ": buildPublicMeta(location.pathname);",
            "document.title = meta.title;",
            "const metaDescriptionTag = ensureMetaDescriptionTag();",
            'metaDescriptionTag.setAttribute("content", meta.description);',
            "}, [location.pathname]);",
            "return location;",
        ],
    )

    require_contains(
        "frontend/src/api/client.js",
        [
            "export async function checkAdminRbac()",
            'return request("/api/v1/admin/rbac-check");',
            "export async function getAdminUsers()",
            "export async function getAdminUserDetail(userId)",
            "export async function createAdminUser(payload)",
            "export async function updateAdminUser(userId, payload)",
            "export async function activateAdminUser(userId)",
            "export async function deactivateAdminUser(userId)",
            "export async function assignAdminUserRole(userId, payload)",
            "export async function removeAdminUserRole(userId, userRoleId)",
            "export async function getAdminOrganizations()",
            "export async function getAdminOrganizationDetail(organizationId)",
            "export async function createAdminOrganization(payload)",
            "export async function updateAdminOrganization(organizationId, payload)",
            "export async function deleteAdminOrganization(organizationId)",
            "export async function getAdminRoles()",
            "export async function getAdminRoleDetail(roleId)",
            "export async function createAdminRole(payload)",
            "export async function updateAdminRole(roleId, payload)",
            "export async function deleteAdminRole(roleId)",
            "export async function assignAdminRolePermission(roleId, payload)",
            "export async function removeAdminRolePermission(roleId, rolePermissionId)",
            "export async function getAdminPermissions()",
            "export async function getAdminPermissionDetail(permissionId)",
            "export async function getAdminAuditEvents(filters = {})",
            "export async function getAdminAuditEventDetail(auditEventId)",
            "export async function getAdminDocuments(filters = {})",
            "export async function getAdminCourses(filters = {})",
            "export async function getAdminEnrollments(filters = {})",
        ],
    )

    print("Admin hooks behavior smoke passed")


if __name__ == "__main__":
    main()
