from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def read_text(relative_path: str) -> str:
    path = ROOT / relative_path

    if not path.exists():
        raise SystemExit(f"File not found: {relative_path}")

    return path.read_text(encoding="utf-8")


def require_contains(relative_path: str, fragments: list[str]) -> None:
    text = read_text(relative_path)
    missing = [fragment for fragment in fragments if fragment not in text]

    if missing:
        print(f"{relative_path} is missing required fragments:")
        for fragment in missing:
            print(f" - {fragment}")
        raise SystemExit(1)


def main() -> None:
    require_contains(
        "frontend/src/utils/adminClasses.js",
        [
            "export const ADMIN_FILTER_CONTROL_CLASS",
            "export const ADMIN_FILTER_CONTROL_WITH_TOP_MARGIN_CLASS",
            "export const ADMIN_FILTER_CONTROL_SOFT_CLASS",
            "export const ADMIN_FILTER_CONTROL_SUBTLE_CLASS",
            "export const ADMIN_FILTER_CONTROL_SUBTLE_DISABLED_CLASS",
            "disabled:bg-slate-50 disabled:text-slate-500",
        ],
    )

    require_contains(
        "frontend/src/utils/adminCollectionState.js",
        [
            "function getCollection(current, collectionKey)",
            "const collection = current?.[collectionKey];",
            "return Array.isArray(collection) ? collection : [];",
            "function applyOptionalSort(items, sortItems)",
            "return typeof sortItems === \"function\" ? sortItems(items) : items;",
            "export function upsertAdminCollectionItem(setAdminData, collectionKey, item, sortItems)",
            "currentItems.filter((currentItem) => currentItem.id !== item.id)",
            "[collectionKey]: applyOptionalSort(nextItems, sortItems)",
            "export function replaceAdminCollectionItem(setAdminData, collectionKey, item, sortItems)",
            "currentItem.id === item.id ? item : currentItem",
            "export function removeAdminCollectionItem(setAdminData, collectionKey, itemId, sortItems)",
            "currentItems.filter((currentItem) => currentItem.id !== itemId)",
        ],
    )

    require_contains(
        "frontend/src/utils/adminLinks.js",
        [
            "export const TABLE_LINK_CLASS",
            "export const LINK_PILL_CLASS",
            "export const PANEL_LINK_CLASS",
            "export function buildPath(pathname, filters = {}, defaults = {})",
            "const params = new URLSearchParams();",
            "Object.entries(filters).forEach(([key, value]) => {",
            "if (!value)",
            "if (defaults[key] !== undefined && String(value) === String(defaults[key]))",
            "params.set(key, value);",
            "return query ? `${pathname}?${query}` : pathname;",
            "export function buildAuditPath(filters = {})",
            "return buildPath(\"/admin/audit-events\", filters,",
            "export function buildUsersPath(filters = {})",
            "return buildPath(\"/admin/users\", filters,",
            "export function buildOrganizationsPath(filters = {})",
            "return buildPath(\"/admin/organizations\", filters,",
            "export function buildGroupsPath(filters = {})",
            "return buildPath(\"/admin/groups\", filters,",
            "organization_id: \"all\"",
            "status: \"all\"",
            "export function buildCoursesPath(filters = {})",
            "export function buildEnrollmentsPath(filters = {})",
            "export function buildDocumentsPath(filters = {})",
            "export function buildRolesPath(filters = {})",
            "export function buildPermissionsPath(filters = {})",
            "export function buildEntityAdminPath(event)",
            "if (!event?.entity_type || !event?.entity_id)",
            "if (event.entity_type === \"user\")",
            "if (event.entity_type === \"organization\")",
            "if (event.entity_type === \"learning_group\")",
            "if (event.entity_type === \"course\")",
            "if (event.entity_type === \"enrollment\")",
            "if (event.entity_type === \"document\")",
            "if (event.entity_type === \"role\")",
            "if (event.entity_type === \"permission\")",
            "export const ADMIN_LINK_BUILDER_DIAGNOSTIC_CASES = [",
            "ENTITY_ADMIN_PATH_DIAGNOSTIC_CASES",
            "expectedPath: \"/admin/audit-events?entity_type=document&limit=25\"",
            "expectedPath: \"/admin/users?activity=inactive\"",
            "expectedPath: \"/admin/groups?status=active&organization_id=00000000-0000-0000-0000-000000000000\"",
            "expectedPath: \"/admin/documents?status=available&type=certificate\"",
            "export function getAdminLinkBuilderDiagnostics()",
            "brokenBuilderCases",
            "duplicateBuilderPaths",
            "export function getEntityAdminPathDiagnostics()",
            "brokenEntityCases",
        ],
    )

    require_contains(
        "frontend/src/utils/adminRoutes.js",
        [
            "export const ADMIN_ROUTE_ITEMS = [",
            "key: \"dashboard\"",
            "path: \"/admin\"",
            "key: \"users\"",
            "path: \"/admin/users\"",
            "key: \"organizations\"",
            "path: \"/admin/organizations\"",
            "key: \"groups\"",
            "path: \"/admin/groups\"",
            "key: \"courses\"",
            "path: \"/admin/courses\"",
            "key: \"enrollments\"",
            "path: \"/admin/enrollments\"",
            "key: \"documents\"",
            "path: \"/admin/documents\"",
            "key: \"roles\"",
            "path: \"/admin/roles\"",
            "key: \"permissions\"",
            "path: \"/admin/permissions\"",
            "key: \"audit\"",
            "path: \"/admin/audit-events\"",
            "export function isAdminPathname(pathname)",
            "return pathname === \"/admin\" || pathname.startsWith(\"/admin/\");",
            "export const ADMIN_ROUTE_PAGE_MAP = ADMIN_ROUTE_ITEMS.reduce((acc, item) => {",
            "acc[item.path] = item.key;",
            "export function getAdminPageFromPathname(pathname)",
            "return ADMIN_ROUTE_PAGE_MAP[pathname] || null;",
            "export function getAdminPathForPage(pageKey)",
            "return ADMIN_ROUTE_ITEMS.find((item) => item.key === pageKey)?.path || \"/admin\";",
        ],
    )

    require_contains(
        "frontend/src/utils/adminState.js",
        [
            "export const EMPTY_ADMIN_DATA = {",
            "users: [],",
            "organizations: [],",
            "groups: [],",
            "courses: [],",
            "enrollments: [],",
            "documents: [],",
            "roles: [],",
            "permissions: [],",
            "auditEvents: [],",
            "export function userHasRole(user, roleCode)",
            "user?.roles?.some((role) => role.code === roleCode) || false",
            "export function getNowLabel()",
            "return new Date().toLocaleString(\"ru-RU\");",
            "export function sortOrganizations(organizations)",
            "left.name.localeCompare(right.name, \"ru-RU\")",
            "export function sortGroups(groups)",
            "export function sortUsers(users)",
            "left.email.localeCompare(right.email, \"ru-RU\")",
            "export function sortRoles(roles)",
            "left.code.localeCompare(right.code, \"ru-RU\")",
        ],
    )

    require_contains(
        "frontend/src/utils/apiErrors.js",
        [
            "export const COMMON_API_ERROR_MESSAGES = {",
            "fallback:",
            "notAuthenticated:",
            "accessDenied:",
            "notFound:",
            "conflict:",
            "invalidRequest:",
            "serverError:",
            "export function getApiErrorMessage(err)",
            "const rawMessage = err?.detail || err?.message || \"\";",
            "if (Array.isArray(rawMessage))",
            ".map((item) => item?.msg || item?.message || JSON.stringify(item))",
            ".join(\"; \");",
            "if (rawMessage && typeof rawMessage === \"object\")",
            "return rawMessage.detail || rawMessage.message || JSON.stringify(rawMessage);",
            "export function formatApiError(err, fallback = COMMON_API_ERROR_MESSAGES.fallback)",
            "const status = err?.status ? `${err.status}` : \"\";",
            "const message = getApiErrorMessage(err);",
            "if (status === \"401\")",
            "else if (status === \"403\")",
            "else if (status === \"404\")",
            "else if (status === \"409\")",
            "else if (status === \"422\")",
            "else if (Number(status) >= 500)",
            "return `${status} ${readableMessage}`.trim();",
        ],
    )

    require_contains(
        "frontend/src/utils/dateFormat.js",
        [
            "export function formatRuDateTime(value, fallback = \"-\")",
            "const date = new Date(value);",
            "if (Number.isNaN(date.getTime()))",
            "new Intl.DateTimeFormat(\"ru-RU\"",
            "dateStyle: \"short\"",
            "timeStyle: \"short\"",
            "export function formatRuDateTimeDash(value)",
            "return formatRuDateTime(value,",
            "export function formatRuDateTimeNative(value, fallback = \"-\")",
            "return date.toLocaleString(\"ru-RU\");",
            "export function formatRuDateTimeNativeUnsafe(value, fallback = \"-\")",
            "return new Date(value).toLocaleString(\"ru-RU\");",
            "export function formatRuLongDate(value, fallback = \"-\")",
            "dateStyle: \"long\"",
        ],
    )

    require_contains(
        "frontend/src/utils/documentVerification.js",
        [
            "export function buildDocumentVerificationPath(code)",
            "if (!code)",
            "return \"/verify-document\";",
            "return `/verify-document?number=${encodeURIComponent(code)}`;",
            "export function buildDocumentVerificationUrl(code)",
            "if (typeof window === \"undefined\")",
            "return buildDocumentVerificationPath(code);",
            "const url = new URL(window.location.href);",
            "url.pathname = \"/verify-document\";",
            "url.searchParams.set(\"number\", code);",
            "return url.toString();",
            "export async function copyTextToClipboard(text)",
            "if (!text)",
            "navigator.clipboard.writeText(text)",
            "const textarea = document.createElement(\"textarea\");",
            "document.body.appendChild(textarea);",
            "document.execCommand(\"copy\")",
            "textarea.remove();",
            "function sanitizeQrFilename(value)",
            ".replace(/[^a-zA-Z0-9",
            ".slice(0, 120)",
            "export function downloadQrSvgById(containerId, filenameBase)",
            "const container = document.getElementById(containerId);",
            "const svg = container?.querySelector(\"svg\");",
            "const clonedSvg = svg.cloneNode(true);",
            "new XMLSerializer().serializeToString(clonedSvg)",
            "new Blob([source], { type: \"image/svg+xml;charset=utf-8\" })",
            "URL.createObjectURL(blob)",
            "link.download = `${sanitizeQrFilename(filenameBase)}.svg`;",
            "URL.revokeObjectURL(objectUrl);",
        ],
    )

    require_contains(
        "frontend/src/utils/organizationCabinet.js",
        [
            "export function formatDate(value)",
            "new Intl.DateTimeFormat(\"ru-RU\"",
            "dateStyle: \"medium\"",
            "timeStyle: \"short\"",
            "export function formatOptional(value)",
            "if (value === undefined || value === null)",
            "if (stringValue.trim() === \"\")",
            "export function shortId(value)",
            "return `${stringValue.slice(0, 8)}",
            "export function formatUserOrganizations(organizations = [], organizationIds = [])",
            "const organizationItems = normalizeItems(organizations);",
            "const organizationIdItems = normalizeItems(organizationIds);",
            "normalizeNestedObject(organization, \"organization\")",
            "export function formatUserRoles(roles = [])",
            "normalizeNestedObject(role, \"role\")",
            "export function buildOrganizationOptions(profileOrganizations = [], groups = [])",
            "const uniqueIds = new Set();",
            "const hasSingleOrganization = organizationIds.length === 1;",
            "function normalizeItems(items)",
            "return Array.isArray(items) ? items : [];",
            "function normalizeObject(item)",
            "function normalizeNestedObject(item, key)",
            "export function buildActiveGroupsCount(groups = [])",
            "export function buildFallbackOrganizationSummary({",
            "organizations_count: organizationItems.length",
            "groups_count: groupItems.length",
            "active_groups_count: activeGroupsCountValue",
            "members_count: 0",
            "export function buildInactiveGroupsCount({",
            "Math.max(totalGroupsCount - activeGroupsCountValue, 0)",
            "export function getOrganizationLabel(organizationId, organizations)",
            "export function getGroupStatus(group)",
            "group?.is_active === true",
            "function buildEnrollmentSortKey(enrollment)",
            "export function sortEnrollments(items)",
            "export function formatEnrollmentStatus(status)",
            "assigned:",
            "in_progress:",
            "completed:",
            "export function mergeUniqueEnrollments(currentItems = [], newItems = [])",
            "const itemsById = new Map();",
            "itemsById.set(item.id, item);",
            "return sortEnrollments([...itemsById.values()]);",
            "export function enrollmentMatchesFilters(enrollment, searchQuery, statusFilter)",
            "if (normalizedStatusFilter && item.status !== normalizedStatusFilter)",
            "searchableText.includes(normalizedSearch)",
            "export function hasActiveEnrollmentFilters(searchQuery, statusFilter)",
            "function buildOrganizationUserSortKey(user)",
            "export function sortOrganizationUsers(items)",
            "export function buildOrganizationUserFromMember(member)",
            "organization_ids: organizations.map((organization) => organization.id)",
            "export function organizationUserMatchesQuery(userItem, query)",
            "function buildMemberSortKey(member)",
            "export function sortMembers(items)",
            "export function buildEmptyGroupEnrollmentForm()",
            "course_id: \"\"",
            "status: \"assigned\"",
            "export function buildEmptyGroupForm(organizationId = \"\")",
            "organization_id: organizationId",
            "is_active: true",
            "export function buildLearningGroupFormData(group)",
            "export function buildOrganizationProfileFormData(organization)",
        ],
    )

    require_contains(
        "frontend/src/utils/organizationCabinetProps.js",
        [
            "export function buildHeroSectionProps({ heroUserLabel, onPageChange, onLogout })",
            "return { heroUserLabel, onPageChange, onLogout };",
            "export function buildCabinetStatsProps({",
            "summary,",
            "organizations,",
            "groups,",
            "activeGroupsCount,",
            "inactiveGroupsCount,",
            "selectedGroup,",
            "selectedGroupId,",
            "members,",
            "export function buildOrganizationProfileSectionProps({",
            "organizations,",
            "onSaveOrganization,",
            "export function buildOrganizationUsersSectionProps({",
            "organizationUsers,",
            "organizationUsersQuery,",
            "organizationUsersLoading,",
            "onSearchOrganizationUsers,",
            "onAddOrganizationUserToSelectedGroup,",
            "setOrganizationUsersQuery,",
            "setOrganizationUsers,",
            "setOrganizationUsersError,",
            "export function buildGroupCreateSectionProps({",
            "groupForm,",
            "creatingGroup,",
            "groupActionError,",
            "groupActionMessage,",
            "onCreateGroup,",
            "onGroupFormChange,",
            "export function buildGroupListProps({",
            "groups,",
            "selectedGroupId,",
            "onSelectGroup,",
            "export function buildGroupsWorkspaceProps({",
            "loading,",
            "hasGroups,",
            "groupListProps,",
            "selectedGroupAsideProps,",
            "export function buildSelectedGroupAsideSectionProps({",
            "selectedGroup,",
            "organizations,",
            "deletingGroupId,",
            "handleDeleteGroup,",
            "handleSaveGroup,",
            "handleCreateGroupEnrollments,",
            "courseSearchQuery,",
            "groupEnrollmentForm,",
            "groupEnrollments,",
            "visibleGroupEnrollments,",
            "members,",
            "handleDeleteMember,",
        ],
    )

    require_contains(
        "frontend/src/utils/publicRoutes.js",
        [
            'import { PUBLIC_COURSES } from "../data/publicCourses";',
            "export const PUBLIC_ROUTE_MAP = {",
            "home: \"/\"",
            "catalog: \"/catalog\"",
            "\"organization-info\": \"/organization-info\"",
            "organization: \"/organization\"",
            "\"verify-document\": \"/verify-document\"",
            "contacts: \"/contacts\"",
            "faq: \"/faq\"",
            "privacy: \"/privacy\"",
            "offer: \"/offer\"",
            "login: \"/login\"",
            "register: \"/register\"",
            "account: \"/account\"",
            "export function getPublicPageFromPathname(pathname)",
            "if (pathname === \"/\") return \"home\";",
            "if (pathname === \"/catalog\") return \"catalog\";",
            "if (pathname.startsWith(\"/courses/\")) return \"course-detail\";",
            "if (pathname === \"/organization-info\") return \"organization-info\";",
            "if (pathname === \"/organization\") return \"organization\";",
            "if (pathname === \"/verify-document\") return \"verify-document\";",
            "if (pathname.startsWith(\"/verify/\")) return \"verify-document\";",
            "if (pathname === \"/contacts\") return \"contacts\";",
            "if (pathname === \"/faq\") return \"faq\";",
            "if (pathname === \"/privacy\") return \"privacy\";",
            "if (pathname === \"/offer\") return \"offer\";",
            "if (pathname === \"/login\") return \"login\";",
            "if (pathname === \"/register\") return \"register\";",
            "if (pathname === \"/account\") return \"account\";",
            "return \"not-found\";",
            "export function ensureMetaDescriptionTag()",
            "document.querySelector('meta[name=\"description\"]')",
            "document.createElement(\"meta\")",
            "document.head.appendChild(element);",
            "export function buildPublicMeta(pathname)",
            "if (pathname === \"/\")",
            "if (pathname === \"/catalog\")",
            "if (pathname.startsWith(\"/courses/\"))",
            "const slug = pathname.replace(/^\\/courses\\//, \"\").replace(/\\/$/, \"\");",
            "PUBLIC_COURSES.find((item) => item.slug === slug)",
            "if (pathname === \"/organization-info\")",
            "if (pathname === \"/verify-document\" || pathname.startsWith(\"/verify/\"))",
            "if (pathname === \"/organization\")",
            "if (pathname === \"/contacts\")",
            "if (pathname === \"/faq\")",
            "if (pathname === \"/privacy\")",
            "if (pathname === \"/offer\")",
            "if (pathname === \"/login\")",
            "if (pathname === \"/register\")",
            "if (pathname === \"/account\")",
            "export const PUBLIC_ROUTE_META_DIAGNOSTIC_CASES = [",
            "expectedPage: \"course-detail\"",
            "expectedPage: \"verify-document\"",
            "expectedPage: \"not-found\"",
            "expectedTitle: \"Страница не найдена — ObrPortal\"",
            "export function getPublicRoutesMetaDiagnostics()",
            "routeMapTotal",
            "metaCasesTotal",
            "duplicatedPaths",
            "brokenMetaCases",
        ],
    )

    require_contains(
        "frontend/src/utils/search.js",
        [
            "export function normalizeSearchValue(value)",
            "return String(value || \"\").trim().toLowerCase();",
            "export function buildSearchText(values)",
            ".map((value) => String(value || \"\").toLowerCase())",
            ".join(\" \");",
        ],
    )

    require_contains(
        "frontend/src/utils/tableText.js",
        [
            "export function getFilteredEmptyText(hasActiveFilters, filteredText, emptyText)",
            "return hasActiveFilters ? filteredText : emptyText;",
            "export function getShownSummary(shownCount, totalCount)",
            "return `",
            "${shownCount}",
            "${totalCount}",
        ],
    )

    require_contains(
        "frontend/src/routes/AdminPageRenderer.jsx",
        [
            'import { AuditPage } from "../pages/AuditPage";',
            'import { DashboardPage } from "../pages/DashboardPage";',
            'import { AdminCoursesPage } from "../pages/AdminCoursesPage";',
            'import { AdminEnrollmentsPage } from "../pages/AdminEnrollmentsPage";',
            'import { DocumentsPage } from "../pages/DocumentsPage";',
            'import { GroupsPage } from "../pages/GroupsPage";',
            'import { OrganizationsPage } from "../pages/OrganizationsPage";',
            'import { PermissionsPage } from "../pages/PermissionsPage";',
            'import { RolesPage } from "../pages/RolesPage";',
            'import { UsersPage } from "../pages/UsersPage";',
            'import { getAdminPageFromPathname } from "../utils/adminRoutes";',
            "export function AdminPageRenderer({",
            "locationPathname,",
            "currentPage,",
            "adminData,",
            "const page = getAdminPageFromPathname(locationPathname) || currentPage;",
            "if (page === \"courses\")",
            "return <AdminCoursesPage />;",
            "if (page === \"enrollments\")",
            "return <AdminEnrollmentsPage />;",
            "if (page === \"users\")",
            "<UsersPage",
            "users={adminData.users}",
            "if (page === \"organizations\")",
            "<OrganizationsPage",
            "organizations={adminData.organizations}",
            "if (page === \"groups\")",
            "<GroupsPage",
            "groups={adminData.groups}",
            "if (page === \"roles\")",
            "<RolesPage",
            "roles={adminData.roles}",
            "permissions={adminData.permissions}",
            "if (page === \"permissions\")",
            "<PermissionsPage",
            "permissions={adminData.permissions}",
            "if (page === \"documents\")",
            "return <DocumentsPage />;",
            "if (page === \"audit\")",
            "<AuditPage",
            "auditEvents={adminData.auditEvents}",
            "<DashboardPage",
        ],
    )

    require_contains(
        "frontend/src/routes/PublicRouteComponents.jsx",
        [
            'import { useParams } from "react-router-dom";',
            'import { CourseDetailPage } from "../pages/CourseDetailPage";',
            'import { VerifyDocumentPage } from "../pages/VerifyDocumentPage";',
            "export function CourseDetailPublicRoute({ onPageChange, onOpenCourse, user })",
            "const { slug } = useParams();",
            "<CourseDetailPage",
            "courseSlug={slug}",
            "onPageChange={onPageChange}",
            "onOpenCourse={onOpenCourse}",
            "user={user}",
            "export function VerifyDocumentCodeRoute({ onPageChange })",
            "const { code } = useParams();",
            "<VerifyDocumentPage onPageChange={onPageChange} initialCode={code || \"\"} />",
        ],
    )

    require_contains(
        "frontend/src/routes/PublicRoutes.jsx",
        [
            'import { Navigate, Route, Routes } from "react-router-dom";',
            'import { AccountPage } from "../pages/AccountPage";',
            'import { AuthPage } from "../pages/AuthPage";',
            'import { CatalogPage } from "../pages/CatalogPage";',
            'import { ContactsPage } from "../pages/ContactsPage";',
            'import { FaqPage } from "../pages/FaqPage";',
            'import { HomePage } from "../pages/HomePage";',
            'import { NotFoundPage } from "../pages/NotFoundPage";',
            'import { OfferPage } from "../pages/OfferPage";',
            'import { OrganizationInfoPage } from "../pages/OrganizationInfoPage";',
            'import { OrganizationCabinetPage } from "../pages/OrganizationCabinetPage";',
            'import { PrivacyPage } from "../pages/PrivacyPage";',
            'import { RegisterPage } from "../pages/RegisterPage";',
            'import { VerifyDocumentPage } from "../pages/VerifyDocumentPage";',
            'import { getAdminPathForPage } from "../utils/adminRoutes";',
            'import { CourseDetailPublicRoute, VerifyDocumentCodeRoute } from "./PublicRouteComponents";',
            'import { userHasRole } from "../utils/adminState";',
            "export function PublicRoutes({",
            "handleNavigatePublicPage,",
            "handleOpenPublicCourse,",
            "const isOrgRepresentative = userHasRole(user, \"org_rep\");",
            "<Routes>",
            "path=\"/\"",
            "<HomePage",
            "path=\"/catalog\"",
            "<CatalogPage",
            "path=\"/courses/:slug\"",
            "<CourseDetailPublicRoute",
            "path=\"/organization-info\"",
            "<OrganizationInfoPage",
            "path=\"/organization\"",
            "isAdmin ?",
            "<Navigate to={getAdminPathForPage(\"dashboard\")} replace />",
            "isOrgRepresentative ?",
            "<OrganizationCabinetPage",
            "<Navigate to=\"/account\" replace />",
            "<Navigate to=\"/login\" replace />",
            "path=\"/verify/:code\"",
            "<VerifyDocumentCodeRoute",
            "path=\"/verify-document\"",
            "<VerifyDocumentPage",
            "path=\"/contacts\"",
            "<ContactsPage",
            "path=\"/faq\"",
            "<FaqPage",
            "path=\"/privacy\"",
            "<PrivacyPage",
            "path=\"/offer\"",
            "<OfferPage",
            "path=\"/login\"",
            "<AuthPage",
            "path=\"/register\"",
            "<RegisterPage",
            "path=\"/account\"",
            "isOrgRepresentative ?",
            "<Navigate to=\"/organization\" replace />",
            "<AccountPage",
            "path=\"*\"",
            "<NotFoundPage",
        ],
    )

    print("Frontend utils/routes behavior smoke passed")


if __name__ == "__main__":
    main()
